-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    gauss_stream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    gauss_stream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_full_n : IN STD_LOGIC;
    gauss_stream_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TREADY : OUT STD_LOGIC );
end;


architecture behav of edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln23_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0 : STD_LOGIC;
    signal gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gauss_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln23_reg_788 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_792 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_stream_read_reg_797 : STD_LOGIC_VECTOR (7 downto 0);
    signal gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802 : STD_LOGIC_VECTOR (10 downto 0);
    signal gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp16_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp16_reg_819 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp10_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp10_reg_824 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_829 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_834 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_834_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal win1_9_reg_839 : STD_LOGIC_VECTOR (7 downto 0);
    signal win0_9_reg_844 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_849 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp41_i_fu_540_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp41_i_reg_854 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln63_2_fu_556_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln63_2_reg_859 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln25_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg13_fu_76 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg12_fu_80 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_10_fu_459_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_addr_reg7_fu_84 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg6_fu_88 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win2_10_fu_470_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_addr_reg_fu_92 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win2_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_fu_108 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal c_fu_112 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln25_fu_383_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_fu_116 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln23_1_fu_423_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_120 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln23_fu_292_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal win2_6_fu_124 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_6_fu_128 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_6_fu_132 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_10_fu_449_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln25_1_fu_301_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_fu_310_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_8_fu_367_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln23_1_fu_417_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_7_fu_430_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal win1_12_cast_i_fu_508_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal win0_13_cast_i_fu_504_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_516_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal win2_13_cast_fu_512_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal win1_14_cast_fu_526_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_530_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_cast_fu_536_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_cast_i_fu_522_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_fu_492_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln63_fu_500_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln63_1_fu_546_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln63_3_fu_552_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_1_fu_496_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_603_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp5_i_fu_614_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln63_cast_i_fu_610_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln53_fu_599_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln63_4_fu_631_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln63_fu_625_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln63_3_fu_634_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln63_2_fu_640_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln63_1_fu_621_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_fu_644_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal and_ln52_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_fu_650_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strdEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component edge_detect_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802,
        ce0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0,
        we0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0,
        d0 => win1_10_fu_459_p3,
        address1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1,
        ce1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1,
        q1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1);

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808,
        ce0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0,
        we0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0,
        d0 => win2_10_fu_470_p3,
        address1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1,
        ce1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1,
        q1 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1);

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strdEe
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0,
        ce0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0,
        we0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0,
        d0 => in_stream_TDATA,
        q0 => gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0);

    flow_control_loop_pipe_sequential_init_U : component edge_detect_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    c_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_112 <= ap_const_lv31_0;
                elsif (((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_112 <= add_ln25_fu_383_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_120 <= ap_const_lv64_0;
                elsif (((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_120 <= add_ln23_fu_292_p2;
                end if;
            end if; 
        end if;
    end process;

    r_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    r_fu_116 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    r_fu_116 <= select_ln23_1_fu_423_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg13_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg13_fu_76 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg13_fu_76 <= zext_ln25_fu_318_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg7_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg7_fu_84 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg7_fu_84 <= zext_ln25_fu_318_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg_fu_92 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_92 <= zext_ln25_fu_318_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg12_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg12_fu_80 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    reuse_reg12_fu_80 <= win1_10_fu_459_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg6_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg6_fu_88 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    reuse_reg6_fu_88 <= win2_10_fu_470_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_96 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    reuse_reg_fu_96 <= in_stream_read_reg_797;
                end if;
            end if; 
        end if;
    end process;

    win0_6_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win0_6_fu_132 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    win0_6_fu_132 <= win0_10_fu_449_p3;
                end if;
            end if; 
        end if;
    end process;

    win0_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win0_fu_108 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    win0_fu_108 <= win0_9_reg_844;
                end if;
            end if; 
        end if;
    end process;

    win1_6_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win1_6_fu_128 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    win1_6_fu_128 <= win1_10_fu_459_p3;
                end if;
            end if; 
        end if;
    end process;

    win1_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win1_fu_104 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    win1_fu_104 <= win1_6_fu_128;
                end if;
            end if; 
        end if;
    end process;

    win2_6_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win2_6_fu_124 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    win2_6_fu_124 <= win2_10_fu_470_p3;
                end if;
            end if; 
        end if;
    end process;

    win2_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win2_fu_100 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
                    win2_fu_100 <= win2_6_fu_124;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln63_2_reg_859 <= add_ln63_2_fu_556_p2;
                icmp_ln52_reg_834_pp0_iter2_reg <= icmp_ln52_reg_834;
                icmp_reg_849 <= icmp_fu_440_p2;
                tmp41_i_reg_854 <= tmp41_i_fu_540_p2;
                win0_9_reg_844 <= win0_6_fu_132;
                win1_9_reg_839 <= win1_6_fu_128;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                addr_cmp10_reg_824 <= addr_cmp10_fu_337_p2;
                addr_cmp16_reg_819 <= addr_cmp16_fu_328_p2;
                addr_cmp_reg_829 <= addr_cmp_fu_346_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808 <= zext_ln25_fu_318_p1(11 - 1 downto 0);
                gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802 <= zext_ln25_fu_318_p1(11 - 1 downto 0);
                icmp_ln23_reg_788 <= icmp_ln23_fu_287_p2;
                icmp_ln25_reg_792 <= icmp_ln25_fu_305_p2;
                icmp_ln52_reg_834 <= icmp_ln52_fu_377_p2;
                in_stream_read_reg_797 <= in_stream_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln23_1_fu_417_p2 <= std_logic_vector(unsigned(r_fu_116) + unsigned(ap_const_lv31_1));
    add_ln23_fu_292_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_120) + unsigned(ap_const_lv64_1));
    add_ln25_fu_383_p2 <= std_logic_vector(unsigned(select_ln23_fu_310_p3) + unsigned(ap_const_lv31_1));
    add_ln63_1_fu_546_p2 <= std_logic_vector(unsigned(zext_ln58_fu_492_p1) + unsigned(zext_ln63_fu_500_p1));
    add_ln63_2_fu_556_p2 <= std_logic_vector(unsigned(zext_ln63_3_fu_552_p1) + unsigned(zext_ln58_1_fu_496_p1));
    add_ln63_3_fu_634_p2 <= std_logic_vector(unsigned(zext_ln63_4_fu_631_p1) + unsigned(add_ln63_fu_625_p2));
    add_ln63_fu_625_p2 <= std_logic_vector(unsigned(shl_ln63_cast_i_fu_610_p1) + unsigned(zext_ln53_fu_599_p1));
    addr_cmp10_fu_337_p2 <= "1" when (reuse_addr_reg7_fu_84 = zext_ln25_fu_318_p1) else "0";
    addr_cmp16_fu_328_p2 <= "1" when (reuse_addr_reg13_fu_76 = zext_ln25_fu_318_p1) else "0";
    addr_cmp_fu_346_p2 <= "1" when (reuse_addr_reg_fu_92 = zext_ln25_fu_318_p1) else "0";
    and_ln52_fu_595_p2 <= (icmp_reg_849 and icmp_ln52_reg_834_pp0_iter2_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(in_stream_TVALID, icmp_ln23_fu_287_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(gauss_stream_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (gauss_stream_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln23_fu_287_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln23_fu_287_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln23_reg_788)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_516_p2 <= std_logic_vector(unsigned(win1_12_cast_i_fu_508_p1) + unsigned(win0_13_cast_i_fu_504_p1));
    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1 <= zext_ln25_fu_318_p1(11 - 1 downto 0);

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln23_reg_788)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0 <= zext_ln25_fu_318_p1(11 - 1 downto 0);

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln23_fu_287_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln23_fu_287_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1 <= zext_ln25_fu_318_p1(11 - 1 downto 0);

    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln23_reg_788)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln23_reg_788 = ap_const_lv1_0))) then 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0 <= ap_const_logic_1;
        else 
            gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, gauss_stream_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            gauss_stream_blk_n <= gauss_stream_full_n;
        else 
            gauss_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    gauss_stream_din <= 
        out_pix_fu_650_p4 when (and_ln52_fu_595_p2(0) = '1') else 
        ap_const_lv8_0;

    gauss_stream_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            gauss_stream_write <= ap_const_logic_1;
        else 
            gauss_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_fu_440_p2 <= "0" when (tmp_7_fu_430_p4 = ap_const_lv30_0) else "1";
    icmp_ln23_fu_287_p2 <= "1" when (indvar_flatten_fu_120 = bound) else "0";
    icmp_ln25_fu_305_p2 <= "1" when (signed(zext_ln25_1_fu_301_p1) < signed(cols)) else "0";
    icmp_ln52_fu_377_p2 <= "0" when (tmp_8_fu_367_p4 = ap_const_lv30_0) else "1";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, icmp_ln23_fu_287_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln23_fu_287_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln23_fu_287_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    out_pix_fu_650_p4 <= sum_fu_644_p2(11 downto 4);
    p_cast_i_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_516_p2),10));
    select_ln23_1_fu_423_p3 <= 
        r_fu_116 when (icmp_ln25_reg_792(0) = '1') else 
        add_ln23_1_fu_417_p2;
    select_ln23_fu_310_p3 <= 
        c_fu_112 when (icmp_ln25_fu_305_p2(0) = '1') else 
        ap_const_lv31_0;
    shl_ln63_cast_i_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_603_p3),11));
    shl_ln_fu_603_p3 <= (win1_9_reg_839 & ap_const_lv2_0);
    sum_fu_644_p2 <= std_logic_vector(unsigned(zext_ln63_2_fu_640_p1) + unsigned(zext_ln63_1_fu_621_p1));
    tmp41_i_fu_540_p2 <= std_logic_vector(unsigned(tmp_cast_fu_536_p1) + unsigned(p_cast_i_fu_522_p1));
    tmp5_i_fu_614_p3 <= (tmp41_i_reg_854 & ap_const_lv1_0);
    tmp_7_fu_430_p4 <= select_ln23_1_fu_423_p3(30 downto 1);
    tmp_8_fu_367_p4 <= select_ln23_fu_310_p3(30 downto 1);
    tmp_cast_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_530_p2),10));
    tmp_fu_530_p2 <= std_logic_vector(unsigned(win2_13_cast_fu_512_p1) + unsigned(win1_14_cast_fu_526_p1));
    win0_10_fu_449_p3 <= 
        reuse_reg12_fu_80 when (addr_cmp16_reg_819(0) = '1') else 
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1;
    win0_13_cast_i_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_6_fu_132),9));
    win1_10_fu_459_p3 <= 
        reuse_reg6_fu_88 when (addr_cmp10_reg_824(0) = '1') else 
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1;
    win1_12_cast_i_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win1_fu_104),9));
    win1_14_cast_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win1_10_fu_459_p3),9));
    win2_10_fu_470_p3 <= 
        reuse_reg_fu_96 when (addr_cmp_reg_829(0) = '1') else 
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0;
    win2_13_cast_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_6_fu_124),9));
    zext_ln25_1_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_112),32));
    zext_ln25_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_fu_310_p3),64));
    zext_ln53_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_fu_108),11));
    zext_ln58_1_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_fu_100),10));
    zext_ln58_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_10_fu_449_p3),9));
    zext_ln63_1_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_i_fu_614_p3),12));
    zext_ln63_2_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_3_fu_634_p2),12));
    zext_ln63_3_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_1_fu_546_p2),10));
    zext_ln63_4_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_2_reg_859),11));
    zext_ln63_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_10_fu_470_p3),9));
end behav;
