-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_detect_sobel_stage is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rows_empty_n : IN STD_LOGIC;
    rows_read : OUT STD_LOGIC;
    cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    cols_empty_n : IN STD_LOGIC;
    cols_read : OUT STD_LOGIC;
    low_thresh_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    low_thresh_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    low_thresh_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    low_thresh_empty_n : IN STD_LOGIC;
    low_thresh_read : OUT STD_LOGIC;
    high_thresh_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    high_thresh_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    high_thresh_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    high_thresh_empty_n : IN STD_LOGIC;
    high_thresh_read : OUT STD_LOGIC;
    gauss_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    gauss_stream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_empty_n : IN STD_LOGIC;
    gauss_stream_read : OUT STD_LOGIC );
end;


architecture behav of edge_detect_sobel_stage is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rows_blk_n : STD_LOGIC;
    signal cols_blk_n : STD_LOGIC;
    signal low_thresh_blk_n : STD_LOGIC;
    signal high_thresh_blk_n : STD_LOGIC;
    signal high_thresh_read_reg_105 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal low_thresh_read_reg_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_read_reg_115 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_read_reg_121 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_92_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_126 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_idle : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID : STD_LOGIC;
    signal grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bound_fu_92_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_92_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_U_vld_out : STD_LOGIC;
    signal bound_fu_92_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_92_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gauss_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        gauss_stream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        gauss_stream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        gauss_stream_empty_n : IN STD_LOGIC;
        gauss_stream_read : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        cols_load : IN STD_LOGIC_VECTOR (31 downto 0);
        high_thresh_load : IN STD_LOGIC_VECTOR (31 downto 0);
        low_thresh_load : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_stream_TVALID : OUT STD_LOGIC );
    end component;


    component edge_detect_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component edge_detect_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74 : component edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start,
        ap_done => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done,
        ap_idle => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_idle,
        ap_ready => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready,
        gauss_stream_dout => gauss_stream_dout,
        gauss_stream_num_data_valid => ap_const_lv7_0,
        gauss_stream_fifo_cap => ap_const_lv7_0,
        gauss_stream_empty_n => gauss_stream_empty_n,
        gauss_stream_read => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read,
        out_stream_TREADY => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY,
        bound => bound_reg_126,
        cols_load => cols_read_reg_115,
        high_thresh_load => high_thresh_read_reg_105,
        low_thresh_load => low_thresh_read_reg_110,
        out_stream_TDATA => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA,
        out_stream_TVALID => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID);

    mul_32ns_32ns_64_1_1_U26 : component edge_detect_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound_fu_92_p0,
        din1 => bound_fu_92_p1,
        dout => bound_fu_92_p2);

    regslice_both_out_stream_U : component edge_detect_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA,
        vld_in => grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_out_stream_U_apdone_blk = ap_const_logic_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_126 <= bound_fu_92_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_read_reg_115 <= cols_dout;
                high_thresh_read_reg_105 <= high_thresh_dout;
                low_thresh_read_reg_110 <= low_thresh_dout;
                rows_read_reg_121 <= rows_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_out_stream_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_out_stream_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done)
    begin
        if ((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_out_stream_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, rows_empty_n, cols_empty_n, low_thresh_empty_n, high_thresh_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (high_thresh_empty_n = ap_const_logic_0) or (low_thresh_empty_n = ap_const_logic_0) or (cols_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, regslice_both_out_stream_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_out_stream_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_out_stream_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_out_stream_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_fu_92_p0 <= bound_fu_92_p00(32 - 1 downto 0);
    bound_fu_92_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rows_read_reg_121),64));
    bound_fu_92_p1 <= bound_fu_92_p10(32 - 1 downto 0);
    bound_fu_92_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cols_read_reg_115),64));

    cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_blk_n <= cols_empty_n;
        else 
            cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    cols_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_read <= ap_const_logic_1;
        else 
            cols_read <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stream_read_assign_proc : process(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            gauss_stream_read <= grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read;
        else 
            gauss_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start <= grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg;
    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state3);

    high_thresh_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, high_thresh_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            high_thresh_blk_n <= high_thresh_empty_n;
        else 
            high_thresh_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    high_thresh_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            high_thresh_read <= ap_const_logic_1;
        else 
            high_thresh_read <= ap_const_logic_0;
        end if; 
    end process;


    low_thresh_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, low_thresh_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            low_thresh_blk_n <= low_thresh_empty_n;
        else 
            low_thresh_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    low_thresh_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            low_thresh_read <= ap_const_logic_1;
        else 
            low_thresh_read <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_U_vld_out;

    rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_blk_n <= rows_empty_n;
        else 
            rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rows_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_read <= ap_const_logic_1;
        else 
            rows_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
