-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_detect_edge_detect_Pipeline_gauss_loop_VITIS_LOOP_28_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln27 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln27 : IN STD_LOGIC_VECTOR (62 downto 0);
    blur_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_ce0 : OUT STD_LOGIC;
    blur_we0 : OUT STD_LOGIC;
    blur_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_1_ce0 : OUT STD_LOGIC;
    blur_1_we0 : OUT STD_LOGIC;
    blur_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_2_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_2_ce0 : OUT STD_LOGIC;
    blur_2_we0 : OUT STD_LOGIC;
    blur_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_3_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_3_ce0 : OUT STD_LOGIC;
    blur_3_we0 : OUT STD_LOGIC;
    blur_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_4_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_4_ce0 : OUT STD_LOGIC;
    blur_4_we0 : OUT STD_LOGIC;
    blur_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_5_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_5_ce0 : OUT STD_LOGIC;
    blur_5_we0 : OUT STD_LOGIC;
    blur_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_6_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_6_ce0 : OUT STD_LOGIC;
    blur_6_we0 : OUT STD_LOGIC;
    blur_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_7_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_7_ce0 : OUT STD_LOGIC;
    blur_7_we0 : OUT STD_LOGIC;
    blur_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    blur_8_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    blur_8_ce0 : OUT STD_LOGIC;
    blur_8_we0 : OUT STD_LOGIC;
    blur_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in_img : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of edge_detect_edge_detect_Pipeline_gauss_loop_VITIS_LOOP_28_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv63_AAAAAAAB : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000010101010101010101010101010101011";
    constant ap_const_lv63_1 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_780 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011110000000";
    constant ap_const_lv32_F00 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000111100000000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal icmp_ln27_reg_848 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_state18_pp0_stage8_iter1 : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage8 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal ap_block_pp0_stage8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal reg_322 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state14_pp0_stage4_iter1 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state15_pp0_stage5_iter1 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage8_11001 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_2_reg_838 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state11_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln28_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_reg_843 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_848_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_848_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln27_3_fu_375_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln27_3_reg_852 : STD_LOGIC_VECTOR (62 downto 0);
    signal select_ln27_fu_402_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_reg_857 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_2_fu_410_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_2_reg_863 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_3_fu_418_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_3_reg_868 : STD_LOGIC_VECTOR (30 downto 0);
    signal gmem_addr_reg_875 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp1_fu_487_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp1_reg_881 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln27_1_fu_492_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln27_1_reg_887 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_state12_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal tmp_24_cast1_reg_894 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_24_cast_reg_899 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_1_reg_904 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_addr_2_reg_910 : STD_LOGIC_VECTOR (63 downto 0);
    signal udiv_ln_cast_reg_916 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_state13_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal add_ln35_1_fu_607_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln35_1_reg_921 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln35_1_reg_921_pp0_iter1_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln35_1_reg_921_pp0_iter2_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln35_1_reg_921_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal sum_reg_926 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_addr_read_reg_931 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_addr_read_1_reg_936 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp8_fu_651_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp8_reg_941 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_1_read_2_reg_946 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state16_pp0_stage6_iter1 : BOOLEAN;
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal gmem_addr_2_read_reg_951 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state17_pp0_stage7_iter1 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal add_ln32_fu_698_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln32_reg_956 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln2_reg_961 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2_reg_961_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_fu_767_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_reg_974 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln35_fu_771_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_23_fu_475_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_25_fu_541_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_27_fu_562_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_126 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln28_fu_612_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal indvar1_fu_130 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln28_1_fu_617_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_fu_134 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal indvar_fu_138 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal indvar_flatten_fu_142 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal trunc_ln28_fu_783_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_317_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln27_fu_498_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln28_3_fu_573_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_317_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln28_2_fu_361_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln27_2_fu_396_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln27_1_fu_390_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_426_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_426_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_shl_fu_436_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal p_shl3_fu_448_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_shl_cast_fu_444_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal p_shl3_cast_fu_456_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal empty_fu_460_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln28_fu_432_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_470_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast_fu_466_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_317_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_525_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_525_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln28_1_fu_522_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_fu_531_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_cast_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp4_fu_552_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_cast_fu_558_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_25_fu_587_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_27_fu_594_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln35_fu_601_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal gmem_addr_1_read_cast_fu_647_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_read_1_cast_fu_644_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_1_read_2_cast_fu_660_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_2_read_1_cast_fu_663_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp9_fu_670_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp9_cast_fu_676_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp8_cast_fu_667_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp41_fu_680_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp5_fu_686_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln32_2_fu_694_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal gmem_addr_read_2_cast_fu_657_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_707_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln32_fu_715_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln32_1_fu_719_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_addr_2_read_2_cast_fu_722_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln32_2_fu_731_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln32_3_fu_737_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln29_fu_704_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln32_3_fu_741_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln32_4_fu_747_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln32_1_fu_726_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_1_fu_751_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_426_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_525_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_426_ce : STD_LOGIC;
    signal grp_fu_525_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component edge_detect_mul_31ns_33ns_63_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (32 downto 0);
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component edge_detect_urem_31ns_3ns_2_35_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component edge_detect_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_31ns_33ns_63_1_1_U1 : component edge_detect_mul_31ns_33ns_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 33,
        dout_WIDTH => 63)
    port map (
        din0 => grp_fu_317_p0,
        din1 => grp_fu_317_p1,
        dout => grp_fu_317_p2);

    urem_31ns_3ns_2_35_1_U2 : component edge_detect_urem_31ns_3ns_2_35_1
    generic map (
        ID => 1,
        NUM_STAGE => 35,
        din0_WIDTH => 31,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_426_p0,
        din1 => grp_fu_426_p1,
        ce => grp_fu_426_ce,
        dout => grp_fu_426_p2);

    urem_31ns_3ns_2_35_1_U3 : component edge_detect_urem_31ns_3ns_2_35_1
    generic map (
        ID => 1,
        NUM_STAGE => 35,
        din0_WIDTH => 31,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_525_p0,
        din1 => grp_fu_525_p1,
        ce => grp_fu_525_ce,
        dout => grp_fu_525_p2);

    flow_control_loop_pipe_sequential_init_U : component edge_detect_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage8,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage8)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    c_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_126 <= ap_const_lv31_1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then 
                    c_fu_126 <= add_ln28_fu_612_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar1_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar1_fu_130 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then 
                    indvar1_fu_130 <= add_ln28_1_fu_617_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_142 <= ap_const_lv63_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_142 <= add_ln27_3_reg_852;
                end if;
            end if; 
        end if;
    end process;

    indvar_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_fu_138 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then 
                    indvar_fu_138 <= select_ln27_2_reg_863;
                end if;
            end if; 
        end if;
    end process;

    r_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_134 <= ap_const_lv31_1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then 
                    r_fu_134 <= select_ln27_3_reg_868;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln27_3_reg_852 <= add_ln27_3_fu_375_p2;
                c_2_reg_838 <= c_fu_126;
                gmem_addr_reg_875 <= empty_23_fu_475_p2;
                icmp_ln27_reg_848 <= icmp_ln27_fu_370_p2;
                icmp_ln27_reg_848_pp0_iter1_reg <= icmp_ln27_reg_848;
                icmp_ln27_reg_848_pp0_iter2_reg <= icmp_ln27_reg_848_pp0_iter1_reg;
                icmp_ln28_reg_843 <= icmp_ln28_fu_365_p2;
                select_ln27_2_reg_863 <= select_ln27_2_fu_410_p3;
                select_ln27_3_reg_868 <= select_ln27_3_fu_418_p3;
                select_ln27_reg_857 <= select_ln27_fu_402_p3;
                tmp1_reg_881 <= tmp1_fu_487_p2;
                trunc_ln2_reg_961 <= sum_1_fu_751_p2(11 downto 4);
                trunc_ln2_reg_961_pp0_iter3_reg <= trunc_ln2_reg_961;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln32_reg_956 <= add_ln32_fu_698_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then
                add_ln35_1_reg_921 <= add_ln35_1_fu_607_p2;
                add_ln35_1_reg_921_pp0_iter1_reg <= add_ln35_1_reg_921;
                add_ln35_1_reg_921_pp0_iter2_reg <= add_ln35_1_reg_921_pp0_iter1_reg;
                add_ln35_1_reg_921_pp0_iter3_reg <= add_ln35_1_reg_921_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001))) then
                gmem_addr_1_read_2_reg_946 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                gmem_addr_1_reg_904 <= empty_25_fu_541_p2;
                gmem_addr_2_reg_910 <= empty_27_fu_562_p2;
                select_ln27_1_reg_887 <= select_ln27_1_fu_492_p3;
                tmp_24_cast1_reg_894 <= grp_fu_317_p2(43 downto 33);
                tmp_24_cast_reg_899 <= grp_fu_317_p2(41 downto 33);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001))) then
                gmem_addr_2_read_reg_951 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                gmem_addr_read_1_reg_936 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                gmem_addr_read_reg_931 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001)))) then
                reg_322 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001)))) then
                reg_326 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                sum_reg_926 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001))) then
                tmp8_reg_941 <= tmp8_fu_651_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then
                trunc_ln27_reg_974 <= trunc_ln27_fu_767_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                udiv_ln_cast_reg_916 <= grp_fu_317_p2(50 downto 33);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage8_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2, ap_idle_pp0_1to4, ap_done_pending_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln27_1_fu_390_p2 <= std_logic_vector(unsigned(r_fu_134) + unsigned(ap_const_lv31_1));
    add_ln27_2_fu_396_p2 <= std_logic_vector(unsigned(indvar_fu_138) + unsigned(ap_const_lv31_1));
    add_ln27_3_fu_375_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_142) + unsigned(ap_const_lv63_1));
    add_ln28_1_fu_617_p2 <= std_logic_vector(unsigned(select_ln27_reg_857) + unsigned(ap_const_lv31_1));
    add_ln28_fu_612_p2 <= std_logic_vector(unsigned(select_ln27_1_reg_887) + unsigned(ap_const_lv31_1));
    add_ln32_1_fu_726_p2 <= std_logic_vector(unsigned(add_ln32_reg_956) + unsigned(zext_ln32_fu_715_p1));
    add_ln32_2_fu_731_p2 <= std_logic_vector(unsigned(zext_ln32_1_fu_719_p1) + unsigned(gmem_addr_2_read_2_cast_fu_722_p1));
    add_ln32_3_fu_741_p2 <= std_logic_vector(unsigned(zext_ln32_3_fu_737_p1) + unsigned(zext_ln29_fu_704_p1));
    add_ln32_fu_698_p2 <= std_logic_vector(unsigned(zext_ln32_2_fu_694_p1) + unsigned(gmem_addr_read_2_cast_fu_657_p1));
    add_ln35_1_fu_607_p2 <= std_logic_vector(unsigned(add_ln35_fu_601_p2) + unsigned(udiv_ln_cast_reg_916));
    add_ln35_fu_601_p2 <= std_logic_vector(unsigned(tmp_25_fu_587_p3) + unsigned(tmp_27_fu_594_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state19_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state19_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter2));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state11_pp0_stage1_iter1)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage1_iter1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state11_pp0_stage1_iter1)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage1_iter1));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state3_io, ap_block_state12_pp0_stage2_iter1)
    begin
                ap_block_pp0_stage2_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage2_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state3_io, ap_block_state12_pp0_stage2_iter1)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage2_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state13_pp0_stage3_iter1)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage3_iter1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state13_pp0_stage3_iter1)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage3_iter1));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state14_pp0_stage4_iter1)
    begin
                ap_block_pp0_stage4_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage4_iter1));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state14_pp0_stage4_iter1)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage4_iter1));
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state6_io, ap_block_state15_pp0_stage5_iter1)
    begin
                ap_block_pp0_stage5_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage5_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;


    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state6_io, ap_block_state15_pp0_stage5_iter1)
    begin
                ap_block_pp0_stage5_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage5_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;

        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state16_pp0_stage6_iter1)
    begin
                ap_block_pp0_stage6_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage6_iter1));
    end process;


    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state16_pp0_stage6_iter1)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage6_iter1));
    end process;

        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage7_iter1)
    begin
                ap_block_pp0_stage7_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage7_iter1));
    end process;


    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage7_iter1)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage7_iter1));
    end process;

        ap_block_pp0_stage8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage8_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state9_io, ap_block_state18_pp0_stage8_iter1)
    begin
                ap_block_pp0_stage8_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage8_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_io)));
    end process;


    ap_block_pp0_stage8_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state9_io, ap_block_state18_pp0_stage8_iter1)
    begin
                ap_block_pp0_stage8_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage8_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_io)));
    end process;


    ap_block_state11_pp0_stage1_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state11_pp0_stage1_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state12_pp0_stage2_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state12_pp0_stage2_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state13_pp0_stage3_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state13_pp0_stage3_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state14_pp0_stage4_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state14_pp0_stage4_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state15_pp0_stage5_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state15_pp0_stage5_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state16_pp0_stage6_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state16_pp0_stage6_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state17_pp0_stage7_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state17_pp0_stage7_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state18_pp0_stage8_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state18_pp0_stage8_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state19_pp0_stage0_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state19_pp0_stage0_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln27_reg_848)
    begin
                ap_block_state3_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln27_reg_848 = ap_const_lv1_0));
    end process;


    ap_block_state6_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln27_reg_848)
    begin
                ap_block_state6_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln27_reg_848 = ap_const_lv1_0));
    end process;


    ap_block_state9_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln27_reg_848)
    begin
                ap_block_state9_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln27_reg_848 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage8_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, icmp_ln27_reg_848, ap_block_pp0_stage8_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (icmp_ln27_reg_848 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln27_reg_848_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln27_reg_848_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage8;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    blur_1_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_1_ce0 <= ap_const_logic_1;
        else 
            blur_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_1_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if (((trunc_ln28_fu_783_p1 = ap_const_lv2_1) and (trunc_ln27_reg_974 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_1_we0 <= ap_const_logic_1;
        else 
            blur_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_2_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_2_ce0 <= ap_const_logic_1;
        else 
            blur_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_2_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if ((not((trunc_ln28_fu_783_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_783_p1 = ap_const_lv2_1)) and (trunc_ln27_reg_974 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_2_we0 <= ap_const_logic_1;
        else 
            blur_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_3_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_3_ce0 <= ap_const_logic_1;
        else 
            blur_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_3_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if (((trunc_ln28_fu_783_p1 = ap_const_lv2_0) and (trunc_ln27_reg_974 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_3_we0 <= ap_const_logic_1;
        else 
            blur_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_4_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_4_ce0 <= ap_const_logic_1;
        else 
            blur_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_4_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if (((trunc_ln28_fu_783_p1 = ap_const_lv2_1) and (trunc_ln27_reg_974 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_4_we0 <= ap_const_logic_1;
        else 
            blur_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_5_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_5_ce0 <= ap_const_logic_1;
        else 
            blur_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_5_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if ((not((trunc_ln28_fu_783_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_783_p1 = ap_const_lv2_1)) and (trunc_ln27_reg_974 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_5_we0 <= ap_const_logic_1;
        else 
            blur_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_6_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_6_ce0 <= ap_const_logic_1;
        else 
            blur_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_6_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if ((not((trunc_ln27_reg_974 = ap_const_lv2_0)) and not((trunc_ln27_reg_974 = ap_const_lv2_1)) and (trunc_ln28_fu_783_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_6_we0 <= ap_const_logic_1;
        else 
            blur_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_7_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_7_ce0 <= ap_const_logic_1;
        else 
            blur_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_7_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if ((not((trunc_ln27_reg_974 = ap_const_lv2_0)) and not((trunc_ln27_reg_974 = ap_const_lv2_1)) and (trunc_ln28_fu_783_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_7_we0 <= ap_const_logic_1;
        else 
            blur_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_8_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_8_ce0 <= ap_const_logic_1;
        else 
            blur_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_8_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if ((not((trunc_ln27_reg_974 = ap_const_lv2_0)) and not((trunc_ln28_fu_783_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_783_p1 = ap_const_lv2_1)) and not((trunc_ln27_reg_974 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_8_we0 <= ap_const_logic_1;
        else 
            blur_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_address0 <= zext_ln35_fu_771_p1(18 - 1 downto 0);

    blur_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_ce0 <= ap_const_logic_1;
        else 
            blur_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    blur_d0 <= trunc_ln2_reg_961_pp0_iter3_reg;

    blur_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, trunc_ln27_reg_974, trunc_ln28_fu_783_p1)
    begin
        if (((trunc_ln28_fu_783_p1 = ap_const_lv2_0) and (trunc_ln27_reg_974 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            blur_we0 <= ap_const_logic_1;
        else 
            blur_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_23_fu_475_p2 <= std_logic_vector(unsigned(tmp_fu_470_p2) + unsigned(p_cast_fu_466_p1));
    empty_25_fu_541_p2 <= std_logic_vector(unsigned(tmp2_cast_fu_537_p1) + unsigned(tmp1_reg_881));
    empty_27_fu_562_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_558_p1) + unsigned(tmp1_reg_881));
    empty_fu_460_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_444_p1) - unsigned(p_shl3_cast_fu_456_p1));
    gmem_addr_1_read_2_cast_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem_addr_1_read_2_reg_946),9));
    gmem_addr_1_read_cast_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_322),9));
    gmem_addr_2_read_1_cast_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_326),9));
    gmem_addr_2_read_2_cast_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_326),9));
    gmem_addr_read_1_cast_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem_addr_read_reg_931),9));
    gmem_addr_read_2_cast_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem_addr_read_1_reg_936),12));

    gmem_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, m_axi_gmem_ARREADY, icmp_ln27_reg_848, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_block_pp0_stage8)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8) and (icmp_ln27_reg_848 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (icmp_ln27_reg_848 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln27_reg_848 = ap_const_lv1_0)))) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage8, m_axi_gmem_RVALID, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_block_pp0_stage8, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3)) or ((ap_enable_reg_pp0_iter1 
    = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2)))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_317_p0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, zext_ln27_fu_498_p1, zext_ln28_3_fu_573_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3))) then 
                grp_fu_317_p0 <= zext_ln28_3_fu_573_p1(31 - 1 downto 0);
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2))) then 
                grp_fu_317_p0 <= zext_ln27_fu_498_p1(31 - 1 downto 0);
            else 
                grp_fu_317_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_317_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_317_p1 <= ap_const_lv63_AAAAAAAB(33 - 1 downto 0);

    grp_fu_426_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage8_11001, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)))) then 
            grp_fu_426_ce <= ap_const_logic_1;
        else 
            grp_fu_426_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_426_p0 <= 
        r_fu_134 when (icmp_ln28_fu_365_p2(0) = '1') else 
        add_ln27_1_fu_390_p2;
    grp_fu_426_p1 <= ap_const_lv31_3(3 - 1 downto 0);

    grp_fu_525_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage8_11001, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)))) then 
            grp_fu_525_ce <= ap_const_logic_1;
        else 
            grp_fu_525_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_525_p0 <= 
        c_2_reg_838 when (icmp_ln28_reg_843(0) = '1') else 
        ap_const_lv31_1;
    grp_fu_525_p1 <= ap_const_lv31_3(3 - 1 downto 0);
    icmp_ln27_fu_370_p2 <= "1" when (indvar_flatten_fu_142 = mul_ln27) else "0";
    icmp_ln28_fu_365_p2 <= "1" when (signed(zext_ln28_2_fu_361_p1) < signed(add_ln27)) else "0";

    m_axi_gmem_ARADDR_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, icmp_ln27_reg_848, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_block_pp0_stage8_11001, gmem_addr_reg_875, ap_block_pp0_stage2_11001, gmem_addr_1_reg_904, gmem_addr_2_reg_910)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln27_reg_848 = ap_const_lv1_0))) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                m_axi_gmem_ARADDR <= gmem_addr_2_reg_910;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001))) then 
                m_axi_gmem_ARADDR <= gmem_addr_1_reg_904;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                m_axi_gmem_ARADDR <= gmem_addr_reg_875;
            else 
                m_axi_gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_3;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, icmp_ln27_reg_848, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_block_pp0_stage8_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001) and (icmp_ln27_reg_848 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (icmp_ln27_reg_848 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln27_reg_848 = ap_const_lv1_0)))) then 
            m_axi_gmem_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage8_11001, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) 
    or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv8_0;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
        p_cast_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_fu_460_p2),64));

    p_shl3_cast_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_fu_448_p3),43));
    p_shl3_fu_448_p3 <= (select_ln27_2_fu_410_p3 & ap_const_lv7_0);
    p_shl_cast_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_436_p3),43));
    p_shl_fu_436_p3 <= (select_ln27_2_fu_410_p3 & ap_const_lv11_0);
    select_ln27_1_fu_492_p3 <= 
        c_2_reg_838 when (icmp_ln28_reg_843(0) = '1') else 
        ap_const_lv31_1;
    select_ln27_2_fu_410_p3 <= 
        indvar_fu_138 when (icmp_ln28_fu_365_p2(0) = '1') else 
        add_ln27_2_fu_396_p2;
    select_ln27_3_fu_418_p3 <= 
        r_fu_134 when (icmp_ln28_fu_365_p2(0) = '1') else 
        add_ln27_1_fu_390_p2;
    select_ln27_fu_402_p3 <= 
        indvar1_fu_130 when (icmp_ln28_fu_365_p2(0) = '1') else 
        ap_const_lv31_0;
    shl_ln_fu_707_p3 <= (reg_322 & ap_const_lv2_0);
    sum_1_fu_751_p2 <= std_logic_vector(unsigned(zext_ln32_4_fu_747_p1) + unsigned(add_ln32_1_fu_726_p2));
    tmp1_fu_487_p2 <= std_logic_vector(signed(p_cast_fu_466_p1) + signed(in_img));
    tmp2_cast_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp2_fu_531_p2),64));
    tmp2_fu_531_p2 <= std_logic_vector(unsigned(zext_ln28_1_fu_522_p1) + unsigned(ap_const_lv32_780));
    tmp41_fu_680_p2 <= std_logic_vector(unsigned(tmp9_cast_fu_676_p1) + unsigned(tmp8_cast_fu_667_p1));
    tmp4_cast_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_552_p2),64));
    tmp4_fu_552_p2 <= std_logic_vector(unsigned(zext_ln28_1_fu_522_p1) + unsigned(ap_const_lv32_F00));
    tmp5_fu_686_p3 <= (tmp41_fu_680_p2 & ap_const_lv1_0);
    tmp8_cast_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp8_reg_941),10));
    tmp8_fu_651_p2 <= std_logic_vector(unsigned(gmem_addr_1_read_cast_fu_647_p1) + unsigned(gmem_addr_read_1_cast_fu_644_p1));
    tmp9_cast_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp9_fu_670_p2),10));
    tmp9_fu_670_p2 <= std_logic_vector(unsigned(gmem_addr_1_read_2_cast_fu_660_p1) + unsigned(gmem_addr_2_read_1_cast_fu_663_p1));
    tmp_25_fu_587_p3 <= (tmp_24_cast_reg_899 & ap_const_lv9_0);
    tmp_27_fu_594_p3 <= (tmp_24_cast1_reg_894 & ap_const_lv7_0);
    tmp_fu_470_p2 <= std_logic_vector(unsigned(zext_ln28_fu_432_p1) + unsigned(in_img));
    trunc_ln27_fu_767_p1 <= grp_fu_426_p2(2 - 1 downto 0);
    trunc_ln28_fu_783_p1 <= grp_fu_525_p2(2 - 1 downto 0);
    zext_ln27_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_3_reg_868),63));
    zext_ln28_1_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_reg_857),32));
    zext_ln28_2_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_126),32));
    zext_ln28_3_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_1_reg_887),63));
    zext_ln28_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_fu_402_p3),64));
    zext_ln29_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_reg_926),10));
    zext_ln32_1_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem_addr_2_read_reg_951),9));
    zext_ln32_2_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_686_p3),12));
    zext_ln32_3_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_2_fu_731_p2),10));
    zext_ln32_4_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_3_fu_741_p2),12));
    zext_ln32_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_707_p3),12));
    zext_ln35_fu_771_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln35_1_reg_921_pp0_iter3_reg),64));
end behav;
