-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    gauss_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    gauss_stream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    gauss_stream_empty_n : IN STD_LOGIC;
    gauss_stream_read : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    cols_load : IN STD_LOGIC_VECTOR (31 downto 0);
    high_thresh_load : IN STD_LOGIC_VECTOR (31 downto 0);
    low_thresh_load : IN STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC );
end;


architecture behav of edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_64 : STD_LOGIC_VECTOR (7 downto 0) := "01100100";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln98_reg_955 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln98_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1 : STD_LOGIC;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gauss_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965 : STD_LOGIC_VECTOR (10 downto 0);
    signal sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp30_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp30_reg_977 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp24_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp24_reg_982 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_reg_992 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_reg_992_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln127_reg_992_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln140_fu_574_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln140_reg_998 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln140_2_fu_612_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln140_2_reg_1003 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln140_1_fu_618_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln140_1_reg_1008 : STD_LOGIC_VECTOR (9 downto 0);
    signal gy_fu_654_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_reg_1013 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln147_fu_787_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_reg_1019 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_reg_1024 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln100_fu_383_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg27_fu_92 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg26_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_5_fu_506_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_addr_reg21_fu_100 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg20_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win2_5_fu_517_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_addr_reg_fu_108 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_112 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win2_fu_116 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_fu_120 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_fu_124 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal c_fu_128 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln100_fu_454_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_fu_132 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln98_1_fu_359_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_136 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln98_fu_324_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal win2_1_fu_140 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win1_1_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_1_fu_148 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal win0_5_fu_496_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln100_1_fu_336_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln100_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln98_1_fu_353_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_fu_367_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln98_fu_345_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_2_fu_432_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln127_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln140_fu_564_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln135_fu_540_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln140_fu_568_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_fu_578_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln140_1_fu_586_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln140_1_fu_590_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln140_1_fu_600_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln140_1_fu_596_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln135_5_fu_556_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln140_2_fu_608_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln135_2_fu_552_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln135_4_fu_560_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln135_1_fu_544_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln141_fu_624_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_630_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln141_1_fu_638_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln141_fu_642_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln135_3_fu_548_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln141_1_fu_648_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln140_3_fu_694_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln140_fu_690_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_697_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln161_fu_710_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln162_fu_716_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_730_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_720_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln141_fu_703_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln161_1_fu_746_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln162_1_fu_751_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln129_fu_707_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_765_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_755_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln163_1_fu_773_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln163_fu_738_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mag_fu_781_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln149_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln147_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln147_fu_802_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln147_1_fu_814_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component edge_detect_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959,
        ce0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0,
        we0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0,
        d0 => win1_5_fu_506_p3,
        address1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1,
        ce1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1,
        q1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1);

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965,
        ce0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0,
        we0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0,
        d0 => win2_5_fu_517_p3,
        address1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1,
        ce1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1,
        q1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1);

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_U : component edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971,
        ce0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0,
        we0 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0,
        d0 => gauss_stream_dout,
        address1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1,
        ce1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1,
        q1 => sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1);

    flow_control_loop_pipe_sequential_init_U : component edge_detect_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    c_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_128 <= ap_const_lv31_0;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_128 <= add_ln100_fu_454_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_136 <= ap_const_lv64_0;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_136 <= add_ln98_fu_324_p2;
                end if;
            end if; 
        end if;
    end process;

    r_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_132 <= ap_const_lv31_0;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    r_fu_132 <= select_ln98_1_fu_359_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg21_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg21_fu_100 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg21_fu_100 <= zext_ln100_fu_383_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg27_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg27_fu_92 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg27_fu_92 <= zext_ln100_fu_383_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg_fu_108 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln98_fu_319_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_108 <= zext_ln100_fu_383_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg20_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg20_fu_104 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_reg20_fu_104 <= win2_5_fu_517_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg26_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg26_fu_96 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_reg26_fu_96 <= win1_5_fu_506_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_112 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_reg_fu_112 <= gauss_stream_dout;
                end if;
            end if; 
        end if;
    end process;

    win0_1_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win0_1_fu_148 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win0_1_fu_148 <= win0_5_fu_496_p3;
                end if;
            end if; 
        end if;
    end process;

    win0_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win0_fu_124 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win0_fu_124 <= win0_1_fu_148;
                end if;
            end if; 
        end if;
    end process;

    win1_1_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win1_1_fu_144 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win1_1_fu_144 <= win1_5_fu_506_p3;
                end if;
            end if; 
        end if;
    end process;

    win1_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win1_fu_120 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win1_fu_120 <= win1_1_fu_144;
                end if;
            end if; 
        end if;
    end process;

    win2_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win2_1_fu_140 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win2_1_fu_140 <= win2_5_fu_517_p3;
                end if;
            end if; 
        end if;
    end process;

    win2_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    win2_fu_116 <= ap_const_lv8_0;
                elsif (((icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    win2_fu_116 <= win2_1_fu_140;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln140_1_reg_1008 <= add_ln140_1_fu_618_p2;
                and_ln127_reg_992_pp0_iter2_reg <= and_ln127_reg_992;
                and_ln127_reg_992_pp0_iter3_reg <= and_ln127_reg_992_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                gy_reg_1013 <= gy_fu_654_p2;
                icmp_ln147_reg_1019 <= icmp_ln147_fu_787_p2;
                icmp_ln149_reg_1024 <= icmp_ln149_fu_792_p2;
                sext_ln140_reg_998 <= sext_ln140_fu_574_p1;
                sub_ln140_2_reg_1003 <= sub_ln140_2_fu_612_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                addr_cmp24_reg_982 <= addr_cmp24_fu_402_p2;
                addr_cmp30_reg_977 <= addr_cmp30_fu_393_p2;
                addr_cmp_reg_987 <= addr_cmp_fu_411_p2;
                and_ln127_reg_992 <= and_ln127_fu_448_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln98_reg_955 <= icmp_ln98_fu_319_p2;
                sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965 <= zext_ln100_fu_383_p1(11 - 1 downto 0);
                sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959 <= zext_ln100_fu_383_p1(11 - 1 downto 0);
                sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971 <= zext_ln100_fu_383_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln100_fu_454_p2 <= std_logic_vector(unsigned(select_ln98_fu_345_p3) + unsigned(ap_const_lv31_1));
    add_ln140_1_fu_618_p2 <= std_logic_vector(unsigned(zext_ln140_2_fu_608_p1) + unsigned(zext_ln135_2_fu_552_p1));
    add_ln140_fu_690_p2 <= std_logic_vector(unsigned(sub_ln140_2_reg_1003) + unsigned(sext_ln140_reg_998));
    add_ln141_fu_642_p2 <= std_logic_vector(signed(sext_ln141_1_fu_638_p1) + signed(zext_ln135_5_fu_556_p1));
    add_ln98_1_fu_353_p2 <= std_logic_vector(unsigned(r_fu_132) + unsigned(ap_const_lv31_1));
    add_ln98_fu_324_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_136) + unsigned(ap_const_lv64_1));
    addr_cmp24_fu_402_p2 <= "1" when (reuse_addr_reg21_fu_100 = zext_ln100_fu_383_p1) else "0";
    addr_cmp30_fu_393_p2 <= "1" when (reuse_addr_reg27_fu_92 = zext_ln100_fu_383_p1) else "0";
    addr_cmp_fu_411_p2 <= "1" when (reuse_addr_reg_fu_108 = zext_ln100_fu_383_p1) else "0";
    and_ln127_fu_448_p2 <= (icmp_ln127_fu_442_p2 and icmp_fu_377_p2);
    and_ln147_fu_810_p2 <= (icmp_ln147_reg_1019 and and_ln127_reg_992_pp0_iter3_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_block_state3_pp0_stage0_iter2, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_block_state3_pp0_stage0_iter2, out_stream_TREADY, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_block_state3_pp0_stage0_iter2, out_stream_TREADY, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(gauss_stream_empty_n, icmp_ln98_reg_955)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln98_reg_955 = ap_const_lv1_0) and (gauss_stream_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln98_fu_319_p2)
    begin
        if (((icmp_ln98_fu_319_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln98_reg_955, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln98_reg_955 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gauss_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, gauss_stream_empty_n, icmp_ln98_reg_955, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gauss_stream_blk_n <= gauss_stream_empty_n;
        else 
            gauss_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gauss_stream_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln98_reg_955, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gauss_stream_read <= ap_const_logic_1;
        else 
            gauss_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    gx_fu_697_p2 <= std_logic_vector(unsigned(zext_ln140_3_fu_694_p1) + unsigned(add_ln140_fu_690_p2));
    gy_fu_654_p2 <= std_logic_vector(unsigned(sub_ln141_1_fu_648_p2) + unsigned(sext_ln140_fu_574_p1));
    icmp_fu_377_p2 <= "0" when (tmp_1_fu_367_p4 = ap_const_lv30_0) else "1";
    icmp_ln100_fu_340_p2 <= "1" when (signed(zext_ln100_1_fu_336_p1) < signed(cols_load)) else "0";
    icmp_ln127_fu_442_p2 <= "0" when (tmp_2_fu_432_p4 = ap_const_lv30_0) else "1";
    icmp_ln147_fu_787_p2 <= "1" when (signed(mag_fu_781_p2) < signed(high_thresh_load)) else "0";
    icmp_ln149_fu_792_p2 <= "1" when (signed(mag_fu_781_p2) < signed(low_thresh_load)) else "0";
    icmp_ln98_fu_319_p2 <= "1" when (indvar_flatten_fu_136 = bound) else "0";
    mag_fu_781_p2 <= std_logic_vector(unsigned(select_ln163_1_fu_773_p3) + unsigned(select_ln163_fu_738_p3));
    out_stream_TDATA <= 
        select_ln147_1_fu_814_p3 when (and_ln127_reg_992_pp0_iter3_reg(0) = '1') else 
        ap_const_lv8_0;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln147_1_fu_814_p3 <= 
        select_ln147_fu_802_p3 when (and_ln147_fu_810_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln147_fu_802_p3 <= 
        ap_const_lv8_64 when (xor_ln149_fu_797_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln163_1_fu_773_p3 <= 
        tmp_5_fu_755_p4 when (tmp_6_fu_765_p3(0) = '1') else 
        sext_ln129_fu_707_p1;
    select_ln163_fu_738_p3 <= 
        tmp_3_fu_720_p4 when (tmp_4_fu_730_p3(0) = '1') else 
        sext_ln141_fu_703_p1;
    select_ln98_1_fu_359_p3 <= 
        r_fu_132 when (icmp_ln100_fu_340_p2(0) = '1') else 
        add_ln98_1_fu_353_p2;
    select_ln98_fu_345_p3 <= 
        c_fu_128 when (icmp_ln100_fu_340_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln129_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_reg_1013),32));

        sext_ln140_1_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln140_1_fu_590_p2),11));

        sext_ln140_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln140_fu_568_p2),11));

        sext_ln141_1_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_630_p3),11));

        sext_ln141_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_fu_697_p2),32));

        sext_ln162_1_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln161_1_fu_746_p2),32));

        sext_ln162_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln161_fu_710_p2),32));

    shl_ln140_1_fu_600_p3 <= (win1_5_fu_506_p3 & ap_const_lv1_0);
    shl_ln_fu_578_p3 <= (win1_fu_120 & ap_const_lv1_0);
    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1 <= zext_ln100_fu_383_p1(11 - 1 downto 0);

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln98_reg_955, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1 <= zext_ln100_fu_383_p1(11 - 1 downto 0);

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln98_reg_955, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1 <= zext_ln100_fu_383_p1(11 - 1 downto 0);

    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln98_reg_955, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln98_reg_955 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0 <= ap_const_logic_1;
        else 
            sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln140_1_fu_590_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(zext_ln140_1_fu_586_p1));
    sub_ln140_2_fu_612_p2 <= std_logic_vector(signed(sext_ln140_1_fu_596_p1) - signed(zext_ln135_5_fu_556_p1));
    sub_ln140_fu_568_p2 <= std_logic_vector(unsigned(zext_ln140_fu_564_p1) - unsigned(zext_ln135_fu_540_p1));
    sub_ln141_1_fu_648_p2 <= std_logic_vector(unsigned(add_ln141_fu_642_p2) - unsigned(zext_ln135_3_fu_548_p1));
    sub_ln141_fu_624_p2 <= std_logic_vector(unsigned(zext_ln135_4_fu_560_p1) - unsigned(zext_ln135_1_fu_544_p1));
    sub_ln161_1_fu_746_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gy_reg_1013));
    sub_ln161_fu_710_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gx_fu_697_p2));
    tmp_1_fu_367_p4 <= select_ln98_1_fu_359_p3(30 downto 1);
    tmp_2_fu_432_p4 <= select_ln98_fu_345_p3(30 downto 1);
    
    tmp_3_fu_720_p4_proc : process(sext_ln162_fu_716_p1)
    begin
        tmp_3_fu_720_p4 <= sext_ln162_fu_716_p1;
        tmp_3_fu_720_p4(31) <= ap_const_lv1_0(0);
    end process;

    tmp_4_fu_730_p3 <= gx_fu_697_p2(10 downto 10);
    
    tmp_5_fu_755_p4_proc : process(sext_ln162_1_fu_751_p1)
    begin
        tmp_5_fu_755_p4 <= sext_ln162_1_fu_751_p1;
        tmp_5_fu_755_p4(31) <= ap_const_lv1_0(0);
    end process;

    tmp_6_fu_765_p3 <= sext_ln129_fu_707_p1(31 downto 31);
    tmp_fu_630_p3 <= (sub_ln141_fu_624_p2 & ap_const_lv1_0);
    win0_5_fu_496_p3 <= 
        reuse_reg26_fu_96 when (addr_cmp30_reg_977(0) = '1') else 
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1;
    win1_5_fu_506_p3 <= 
        reuse_reg20_fu_104 when (addr_cmp24_reg_982(0) = '1') else 
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1;
    win2_5_fu_517_p3 <= 
        reuse_reg_fu_112 when (addr_cmp_reg_987(0) = '1') else 
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1;
    xor_ln149_fu_797_p2 <= (icmp_ln149_reg_1024 xor ap_const_lv1_1);
    zext_ln100_1_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_128),32));
    zext_ln100_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln98_fu_345_p3),64));
    zext_ln135_1_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_1_fu_148),9));
    zext_ln135_2_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_5_fu_496_p3),10));
    zext_ln135_3_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_5_fu_496_p3),11));
    zext_ln135_4_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_1_fu_140),9));
    zext_ln135_5_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_fu_116),11));
    zext_ln135_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win0_fu_124),9));
    zext_ln140_1_fu_586_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_578_p3),10));
    zext_ln140_2_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln140_1_fu_600_p3),10));
    zext_ln140_3_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln140_1_reg_1008),11));
    zext_ln140_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win2_5_fu_517_p3),9));
end behav;
