// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_gauss_stage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        rows,
        cols,
        rows_c_din,
        rows_c_num_data_valid,
        rows_c_fifo_cap,
        rows_c_full_n,
        rows_c_write,
        cols_c_din,
        cols_c_num_data_valid,
        cols_c_fifo_cap,
        cols_c_full_n,
        cols_c_write,
        gauss_stream_din,
        gauss_stream_num_data_valid,
        gauss_stream_fifo_cap,
        gauss_stream_full_n,
        gauss_stream_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [31:0] rows;
input  [31:0] cols;
output  [31:0] rows_c_din;
input  [2:0] rows_c_num_data_valid;
input  [2:0] rows_c_fifo_cap;
input   rows_c_full_n;
output   rows_c_write;
output  [31:0] cols_c_din;
input  [2:0] cols_c_num_data_valid;
input  [2:0] cols_c_fifo_cap;
input   cols_c_full_n;
output   cols_c_write;
output  [7:0] gauss_stream_din;
input  [6:0] gauss_stream_num_data_valid;
input  [6:0] gauss_stream_fifo_cap;
input   gauss_stream_full_n;
output   gauss_stream_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rows_c_write;
reg cols_c_write;
reg gauss_stream_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    rows_c_blk_n;
reg    cols_c_blk_n;
reg    ap_block_state1;
wire   [63:0] bound_fu_96_p2;
reg   [63:0] bound_reg_115;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_idle;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_ready;
wire   [7:0] grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_din;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_write;
wire    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_in_stream_TREADY;
reg    grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] bound_fu_96_p0;
wire   [31:0] bound_fu_96_p1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_in_stream_U_apdone_blk;
wire   [7:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_U_ack_in;
wire   [63:0] bound_fu_96_p00;
wire   [63:0] bound_fu_96_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg = 1'b0;
end

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start),
    .ap_done(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done),
    .ap_idle(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_idle),
    .ap_ready(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .gauss_stream_din(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_din),
    .gauss_stream_num_data_valid(7'd0),
    .gauss_stream_fifo_cap(7'd0),
    .gauss_stream_full_n(gauss_stream_full_n),
    .gauss_stream_write(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_write),
    .bound(bound_reg_115),
    .cols(cols),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_in_stream_TREADY)
);

edge_detect_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U11(
    .din0(bound_fu_96_p0),
    .din1(bound_fu_96_p1),
    .dout(bound_fu_96_p2)
);

edge_detect_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_ready == 1'b1)) begin
            grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_reg_115 <= bound_fu_96_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c_blk_n = cols_c_full_n;
    end else begin
        cols_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_c_write = 1'b1;
    end else begin
        cols_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gauss_stream_write = grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_write;
    end else begin
        gauss_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c_blk_n = rows_c_full_n;
    end else begin
        rows_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_c_write = 1'b1;
    end else begin
        rows_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (cols_c_full_n == 1'b0) | (rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign bound_fu_96_p0 = bound_fu_96_p00;

assign bound_fu_96_p00 = rows;

assign bound_fu_96_p1 = bound_fu_96_p10;

assign bound_fu_96_p10 = cols;

assign cols_c_din = cols;

assign gauss_stream_din = grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_gauss_stream_din;

assign grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start = grp_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_fu_80_ap_start_reg;

assign in_stream_TREADY = regslice_both_in_stream_U_ack_in;

assign rows_c_din = rows;

endmodule //edge_detect_gauss_stage
