// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        gauss_stream_din,
        gauss_stream_num_data_valid,
        gauss_stream_fifo_cap,
        gauss_stream_full_n,
        gauss_stream_write,
        bound,
        cols,
        in_stream_TDATA,
        in_stream_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [7:0] gauss_stream_din;
input  [6:0] gauss_stream_num_data_valid;
input  [6:0] gauss_stream_fifo_cap;
input   gauss_stream_full_n;
output   gauss_stream_write;
input  [63:0] bound;
input  [31:0] cols;
input  [7:0] in_stream_TDATA;
output   in_stream_TREADY;

reg ap_idle;
reg gauss_stream_write;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln23_fu_287_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0;
wire   [10:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1;
wire   [7:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0;
wire   [10:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1;
wire   [7:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1;
wire   [10:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0;
reg    gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0;
wire   [7:0] gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    gauss_stream_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln23_reg_788;
wire   [0:0] icmp_ln25_fu_305_p2;
reg   [0:0] icmp_ln25_reg_792;
reg   [7:0] in_stream_read_reg_797;
reg   [10:0] gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802;
reg   [10:0] gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808;
wire   [0:0] addr_cmp16_fu_328_p2;
reg   [0:0] addr_cmp16_reg_819;
wire   [0:0] addr_cmp10_fu_337_p2;
reg   [0:0] addr_cmp10_reg_824;
wire   [0:0] addr_cmp_fu_346_p2;
reg   [0:0] addr_cmp_reg_829;
wire   [0:0] icmp_ln52_fu_377_p2;
reg   [0:0] icmp_ln52_reg_834;
reg   [0:0] icmp_ln52_reg_834_pp0_iter2_reg;
reg   [7:0] win1_9_reg_839;
reg   [7:0] win0_9_reg_844;
wire   [0:0] icmp_fu_440_p2;
reg   [0:0] icmp_reg_849;
wire   [9:0] tmp41_i_fu_540_p2;
reg   [9:0] tmp41_i_reg_854;
wire   [9:0] add_ln63_2_fu_556_p2;
reg   [9:0] add_ln63_2_reg_859;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln25_fu_318_p1;
reg   [63:0] reuse_addr_reg13_fu_76;
wire    ap_loop_init;
reg   [7:0] reuse_reg12_fu_80;
wire   [7:0] win1_10_fu_459_p3;
reg   [63:0] reuse_addr_reg7_fu_84;
reg   [7:0] reuse_reg6_fu_88;
wire   [7:0] win2_10_fu_470_p3;
reg   [63:0] reuse_addr_reg_fu_92;
reg   [7:0] reuse_reg_fu_96;
reg   [7:0] win2_fu_100;
reg   [7:0] win1_fu_104;
reg   [7:0] win0_fu_108;
reg   [30:0] c_fu_112;
wire   [30:0] add_ln25_fu_383_p2;
reg   [30:0] r_fu_116;
wire   [30:0] select_ln23_1_fu_423_p3;
reg   [63:0] indvar_flatten_fu_120;
wire   [63:0] add_ln23_fu_292_p2;
reg   [7:0] win2_6_fu_124;
reg   [7:0] win1_6_fu_128;
reg   [7:0] win0_6_fu_132;
wire   [7:0] win0_10_fu_449_p3;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln25_1_fu_301_p1;
wire   [30:0] select_ln23_fu_310_p3;
wire   [29:0] tmp_8_fu_367_p4;
wire   [30:0] add_ln23_1_fu_417_p2;
wire   [29:0] tmp_7_fu_430_p4;
wire   [8:0] win1_12_cast_i_fu_508_p1;
wire   [8:0] win0_13_cast_i_fu_504_p1;
wire   [8:0] empty_fu_516_p2;
wire   [8:0] win2_13_cast_fu_512_p1;
wire   [8:0] win1_14_cast_fu_526_p1;
wire   [8:0] tmp_fu_530_p2;
wire   [9:0] tmp_cast_fu_536_p1;
wire   [9:0] p_cast_i_fu_522_p1;
wire   [8:0] zext_ln58_fu_492_p1;
wire   [8:0] zext_ln63_fu_500_p1;
wire   [8:0] add_ln63_1_fu_546_p2;
wire   [9:0] zext_ln63_3_fu_552_p1;
wire   [9:0] zext_ln58_1_fu_496_p1;
wire   [9:0] shl_ln_fu_603_p3;
wire   [10:0] tmp5_i_fu_614_p3;
wire   [10:0] shl_ln63_cast_i_fu_610_p1;
wire   [10:0] zext_ln53_fu_599_p1;
wire   [10:0] zext_ln63_4_fu_631_p1;
wire   [10:0] add_ln63_fu_625_p2;
wire   [10:0] add_ln63_3_fu_634_p2;
wire   [11:0] zext_ln63_2_fu_640_p1;
wire   [11:0] zext_ln63_1_fu_621_p1;
wire   [11:0] sum_fu_644_p2;
wire   [0:0] and_ln52_fu_595_p2;
wire   [7:0] out_pix_fu_650_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 reuse_addr_reg13_fu_76 = 64'd0;
#0 reuse_reg12_fu_80 = 8'd0;
#0 reuse_addr_reg7_fu_84 = 64'd0;
#0 reuse_reg6_fu_88 = 8'd0;
#0 reuse_addr_reg_fu_92 = 64'd0;
#0 reuse_reg_fu_96 = 8'd0;
#0 win2_fu_100 = 8'd0;
#0 win1_fu_104 = 8'd0;
#0 win0_fu_108 = 8'd0;
#0 c_fu_112 = 31'd0;
#0 r_fu_116 = 31'd0;
#0 indvar_flatten_fu_120 = 64'd0;
#0 win2_6_fu_124 = 8'd0;
#0 win1_6_fu_128 = 8'd0;
#0 win0_6_fu_132 = 8'd0;
#0 ap_done_reg = 1'b0;
end

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802),
    .ce0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0),
    .we0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0),
    .d0(win1_10_fu_459_p3),
    .address1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1),
    .ce1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1),
    .q1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1)
);

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808),
    .ce0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0),
    .we0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0),
    .d0(win2_10_fu_470_p3),
    .address1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1),
    .ce1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1),
    .q1(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1)
);

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strdEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0),
    .ce0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0),
    .we0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0),
    .d0(in_stream_TDATA),
    .q0(gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0)
);

edge_detect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_112 <= 31'd0;
        end else if (((icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_112 <= add_ln25_fu_383_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_120 <= 64'd0;
        end else if (((icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_120 <= add_ln23_fu_292_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            r_fu_116 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            r_fu_116 <= select_ln23_1_fu_423_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg13_fu_76 <= 64'd18446744073709551615;
        end else if (((icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg13_fu_76 <= zext_ln25_fu_318_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg7_fu_84 <= 64'd18446744073709551615;
        end else if (((icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg7_fu_84 <= zext_ln25_fu_318_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_92 <= 64'd18446744073709551615;
        end else if (((icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg_fu_92 <= zext_ln25_fu_318_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg12_fu_80 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            reuse_reg12_fu_80 <= win1_10_fu_459_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg6_fu_88 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            reuse_reg6_fu_88 <= win2_10_fu_470_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_96 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            reuse_reg_fu_96 <= in_stream_read_reg_797;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win0_6_fu_132 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            win0_6_fu_132 <= win0_10_fu_449_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win0_fu_108 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            win0_fu_108 <= win0_9_reg_844;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win1_6_fu_128 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            win1_6_fu_128 <= win1_10_fu_459_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win1_fu_104 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            win1_fu_104 <= win1_6_fu_128;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win2_6_fu_124 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            win2_6_fu_124 <= win2_10_fu_470_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win2_fu_100 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
            win2_fu_100 <= win2_6_fu_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln63_2_reg_859 <= add_ln63_2_fu_556_p2;
        icmp_ln52_reg_834_pp0_iter2_reg <= icmp_ln52_reg_834;
        icmp_reg_849 <= icmp_fu_440_p2;
        tmp41_i_reg_854 <= tmp41_i_fu_540_p2;
        win0_9_reg_844 <= win0_6_fu_132;
        win1_9_reg_839 <= win1_6_fu_128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_cmp10_reg_824 <= addr_cmp10_fu_337_p2;
        addr_cmp16_reg_819 <= addr_cmp16_fu_328_p2;
        addr_cmp_reg_829 <= addr_cmp_fu_346_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_3_addr_reg_808 <= zext_ln25_fu_318_p1;
        gauss_stage_stream_ap_uint_0_stream_ap_uint_8_0_int_int_linebuf_addr_reg_802 <= zext_ln25_fu_318_p1;
        icmp_ln23_reg_788 <= icmp_ln23_fu_287_p2;
        icmp_ln25_reg_792 <= icmp_ln25_fu_305_p2;
        icmp_ln52_reg_834 <= icmp_ln52_fu_377_p2;
        in_stream_read_reg_797 <= in_stream_TDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln23_fu_287_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln23_reg_788 == 1'd0))) begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0 = 1'b1;
    end else begin
        gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        gauss_stream_blk_n = gauss_stream_full_n;
    end else begin
        gauss_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        gauss_stream_write = 1'b1;
    end else begin
        gauss_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln23_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_1_fu_417_p2 = (r_fu_116 + 31'd1);

assign add_ln23_fu_292_p2 = (indvar_flatten_fu_120 + 64'd1);

assign add_ln25_fu_383_p2 = (select_ln23_fu_310_p3 + 31'd1);

assign add_ln63_1_fu_546_p2 = (zext_ln58_fu_492_p1 + zext_ln63_fu_500_p1);

assign add_ln63_2_fu_556_p2 = (zext_ln63_3_fu_552_p1 + zext_ln58_1_fu_496_p1);

assign add_ln63_3_fu_634_p2 = (zext_ln63_4_fu_631_p1 + add_ln63_fu_625_p2);

assign add_ln63_fu_625_p2 = (shl_ln63_cast_i_fu_610_p1 + zext_ln53_fu_599_p1);

assign addr_cmp10_fu_337_p2 = ((reuse_addr_reg7_fu_84 == zext_ln25_fu_318_p1) ? 1'b1 : 1'b0);

assign addr_cmp16_fu_328_p2 = ((reuse_addr_reg13_fu_76 == zext_ln25_fu_318_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_346_p2 = ((reuse_addr_reg_fu_92 == zext_ln25_fu_318_p1) ? 1'b1 : 1'b0);

assign and_ln52_fu_595_p2 = (icmp_reg_849 & icmp_ln52_reg_834_pp0_iter2_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln23_fu_287_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (gauss_stream_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_fu_516_p2 = (win1_12_cast_i_fu_508_p1 + win0_13_cast_i_fu_504_p1);

assign gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_address1 = zext_ln25_fu_318_p1;

assign gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_address0 = zext_ln25_fu_318_p1;

assign gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_address1 = zext_ln25_fu_318_p1;

assign gauss_stream_din = ((and_ln52_fu_595_p2[0:0] == 1'b1) ? out_pix_fu_650_p4 : 8'd0);

assign icmp_fu_440_p2 = ((tmp_7_fu_430_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_287_p2 = ((indvar_flatten_fu_120 == bound) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_305_p2 = (($signed(zext_ln25_1_fu_301_p1) < $signed(cols)) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_377_p2 = ((tmp_8_fu_367_p4 != 30'd0) ? 1'b1 : 1'b0);

assign out_pix_fu_650_p4 = {{sum_fu_644_p2[11:4]}};

assign p_cast_i_fu_522_p1 = empty_fu_516_p2;

assign select_ln23_1_fu_423_p3 = ((icmp_ln25_reg_792[0:0] == 1'b1) ? r_fu_116 : add_ln23_1_fu_417_p2);

assign select_ln23_fu_310_p3 = ((icmp_ln25_fu_305_p2[0:0] == 1'b1) ? c_fu_112 : 31'd0);

assign shl_ln63_cast_i_fu_610_p1 = shl_ln_fu_603_p3;

assign shl_ln_fu_603_p3 = {{win1_9_reg_839}, {2'd0}};

assign sum_fu_644_p2 = (zext_ln63_2_fu_640_p1 + zext_ln63_1_fu_621_p1);

assign tmp41_i_fu_540_p2 = (tmp_cast_fu_536_p1 + p_cast_i_fu_522_p1);

assign tmp5_i_fu_614_p3 = {{tmp41_i_reg_854}, {1'd0}};

assign tmp_7_fu_430_p4 = {{select_ln23_1_fu_423_p3[30:1]}};

assign tmp_8_fu_367_p4 = {{select_ln23_fu_310_p3[30:1]}};

assign tmp_cast_fu_536_p1 = tmp_fu_530_p2;

assign tmp_fu_530_p2 = (win2_13_cast_fu_512_p1 + win1_14_cast_fu_526_p1);

assign win0_10_fu_449_p3 = ((addr_cmp16_reg_819[0:0] == 1'b1) ? reuse_reg12_fu_80 : gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_q1);

assign win0_13_cast_i_fu_504_p1 = win0_6_fu_132;

assign win1_10_fu_459_p3 = ((addr_cmp10_reg_824[0:0] == 1'b1) ? reuse_reg6_fu_88 : gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_3_q1);

assign win1_12_cast_i_fu_508_p1 = win1_fu_104;

assign win1_14_cast_fu_526_p1 = win1_10_fu_459_p3;

assign win2_10_fu_470_p3 = ((addr_cmp_reg_829[0:0] == 1'b1) ? reuse_reg_fu_96 : gauss_stage_stream_ap_uint_8_0_stream_ap_uint_8_0_int_int_linebuf_4_q0);

assign win2_13_cast_fu_512_p1 = win2_6_fu_124;

assign zext_ln25_1_fu_301_p1 = c_fu_112;

assign zext_ln25_fu_318_p1 = select_ln23_fu_310_p3;

assign zext_ln53_fu_599_p1 = win0_fu_108;

assign zext_ln58_1_fu_496_p1 = win2_fu_100;

assign zext_ln58_fu_492_p1 = win0_10_fu_449_p3;

assign zext_ln63_1_fu_621_p1 = tmp5_i_fu_614_p3;

assign zext_ln63_2_fu_640_p1 = add_ln63_3_fu_634_p2;

assign zext_ln63_3_fu_552_p1 = add_ln63_1_fu_546_p2;

assign zext_ln63_4_fu_631_p1 = add_ln63_2_reg_859;

assign zext_ln63_fu_500_p1 = win2_10_fu_470_p3;

endmodule //edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G
