// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_sobel_stage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        rows_dout,
        rows_num_data_valid,
        rows_fifo_cap,
        rows_empty_n,
        rows_read,
        cols_dout,
        cols_num_data_valid,
        cols_fifo_cap,
        cols_empty_n,
        cols_read,
        low_thresh_dout,
        low_thresh_num_data_valid,
        low_thresh_fifo_cap,
        low_thresh_empty_n,
        low_thresh_read,
        high_thresh_dout,
        high_thresh_num_data_valid,
        high_thresh_fifo_cap,
        high_thresh_empty_n,
        high_thresh_read,
        gauss_stream_dout,
        gauss_stream_num_data_valid,
        gauss_stream_fifo_cap,
        gauss_stream_empty_n,
        gauss_stream_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
input  [31:0] rows_dout;
input  [2:0] rows_num_data_valid;
input  [2:0] rows_fifo_cap;
input   rows_empty_n;
output   rows_read;
input  [31:0] cols_dout;
input  [2:0] cols_num_data_valid;
input  [2:0] cols_fifo_cap;
input   cols_empty_n;
output   cols_read;
input  [31:0] low_thresh_dout;
input  [2:0] low_thresh_num_data_valid;
input  [2:0] low_thresh_fifo_cap;
input   low_thresh_empty_n;
output   low_thresh_read;
input  [31:0] high_thresh_dout;
input  [2:0] high_thresh_num_data_valid;
input  [2:0] high_thresh_fifo_cap;
input   high_thresh_empty_n;
output   high_thresh_read;
input  [7:0] gauss_stream_dout;
input  [6:0] gauss_stream_num_data_valid;
input  [6:0] gauss_stream_fifo_cap;
input   gauss_stream_empty_n;
output   gauss_stream_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rows_read;
reg cols_read;
reg low_thresh_read;
reg high_thresh_read;
reg gauss_stream_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    rows_blk_n;
reg    cols_blk_n;
reg    low_thresh_blk_n;
reg    high_thresh_blk_n;
reg   [31:0] high_thresh_read_reg_105;
reg    ap_block_state1;
reg   [31:0] low_thresh_read_reg_110;
reg   [31:0] cols_read_reg_115;
reg   [31:0] rows_read_reg_121;
wire   [63:0] bound_fu_92_p2;
reg   [63:0] bound_reg_126;
wire    ap_CS_fsm_state2;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_idle;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY;
wire   [7:0] grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA;
wire    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID;
reg    grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [31:0] bound_fu_92_p0;
wire   [31:0] bound_fu_92_p1;
wire    ap_CS_fsm_state4;
wire    regslice_both_out_stream_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_U_vld_out;
wire   [63:0] bound_fu_92_p00;
wire   [63:0] bound_fu_92_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg = 1'b0;
end

edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start),
    .ap_done(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done),
    .ap_idle(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_idle),
    .ap_ready(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready),
    .gauss_stream_dout(gauss_stream_dout),
    .gauss_stream_num_data_valid(7'd0),
    .gauss_stream_fifo_cap(7'd0),
    .gauss_stream_empty_n(gauss_stream_empty_n),
    .gauss_stream_read(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read),
    .out_stream_TREADY(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY),
    .bound(bound_reg_126),
    .cols_load(cols_read_reg_115),
    .high_thresh_load(high_thresh_read_reg_105),
    .low_thresh_load(low_thresh_read_reg_110),
    .out_stream_TDATA(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA),
    .out_stream_TVALID(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID)
);

edge_detect_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U26(
    .din0(bound_fu_92_p0),
    .din1(bound_fu_92_p1),
    .dout(bound_fu_92_p2)
);

edge_detect_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TDATA),
    .vld_in(grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_out_stream_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_ready == 1'b1)) begin
            grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_126 <= bound_fu_92_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_read_reg_115 <= cols_dout;
        high_thresh_read_reg_105 <= high_thresh_dout;
        low_thresh_read_reg_110 <= low_thresh_dout;
        rows_read_reg_121 <= rows_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_out_stream_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_out_stream_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_blk_n = cols_empty_n;
    end else begin
        cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_read = 1'b1;
    end else begin
        cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gauss_stream_read = grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_gauss_stream_read;
    end else begin
        gauss_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        high_thresh_blk_n = high_thresh_empty_n;
    end else begin
        high_thresh_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        high_thresh_read = 1'b1;
    end else begin
        high_thresh_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        low_thresh_blk_n = low_thresh_empty_n;
    end else begin
        low_thresh_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        low_thresh_read = 1'b1;
    end else begin
        low_thresh_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_blk_n = rows_empty_n;
    end else begin
        rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_read = 1'b1;
    end else begin
        rows_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_out_stream_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (high_thresh_empty_n == 1'b0) | (low_thresh_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign bound_fu_92_p0 = bound_fu_92_p00;

assign bound_fu_92_p00 = rows_read_reg_121;

assign bound_fu_92_p1 = bound_fu_92_p10;

assign bound_fu_92_p10 = cols_read_reg_115;

assign grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start = grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_ap_start_reg;

assign grp_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S_fu_74_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state3);

assign out_stream_TVALID = regslice_both_out_stream_U_vld_out;

endmodule //edge_detect_sobel_stage
