// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        gauss_stream_dout,
        gauss_stream_num_data_valid,
        gauss_stream_fifo_cap,
        gauss_stream_empty_n,
        gauss_stream_read,
        out_stream_TREADY,
        bound,
        cols_load,
        high_thresh_load,
        low_thresh_load,
        out_stream_TDATA,
        out_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] gauss_stream_dout;
input  [6:0] gauss_stream_num_data_valid;
input  [6:0] gauss_stream_fifo_cap;
input   gauss_stream_empty_n;
output   gauss_stream_read;
input   out_stream_TREADY;
input  [63:0] bound;
input  [31:0] cols_load;
input  [31:0] high_thresh_load;
input  [31:0] low_thresh_load;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;

reg ap_idle;
reg gauss_stream_read;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln98_reg_955;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln98_fu_319_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0;
wire   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1;
wire   [7:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0;
wire   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1;
wire   [7:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0;
wire   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1;
reg    sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1;
wire   [7:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    gauss_stream_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959;
reg   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965;
reg   [10:0] sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971;
wire   [0:0] addr_cmp30_fu_393_p2;
reg   [0:0] addr_cmp30_reg_977;
wire   [0:0] addr_cmp24_fu_402_p2;
reg   [0:0] addr_cmp24_reg_982;
wire   [0:0] addr_cmp_fu_411_p2;
reg   [0:0] addr_cmp_reg_987;
wire   [0:0] and_ln127_fu_448_p2;
reg   [0:0] and_ln127_reg_992;
reg   [0:0] and_ln127_reg_992_pp0_iter2_reg;
reg   [0:0] and_ln127_reg_992_pp0_iter3_reg;
wire  signed [10:0] sext_ln140_fu_574_p1;
reg  signed [10:0] sext_ln140_reg_998;
wire   [10:0] sub_ln140_2_fu_612_p2;
reg   [10:0] sub_ln140_2_reg_1003;
wire   [9:0] add_ln140_1_fu_618_p2;
reg   [9:0] add_ln140_1_reg_1008;
wire  signed [10:0] gy_fu_654_p2;
reg  signed [10:0] gy_reg_1013;
wire   [0:0] icmp_ln147_fu_787_p2;
reg   [0:0] icmp_ln147_reg_1019;
wire   [0:0] icmp_ln149_fu_792_p2;
reg   [0:0] icmp_ln149_reg_1024;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln100_fu_383_p1;
reg   [63:0] reuse_addr_reg27_fu_92;
wire    ap_loop_init;
reg   [7:0] reuse_reg26_fu_96;
wire   [7:0] win1_5_fu_506_p3;
reg   [63:0] reuse_addr_reg21_fu_100;
reg   [7:0] reuse_reg20_fu_104;
wire   [7:0] win2_5_fu_517_p3;
reg   [63:0] reuse_addr_reg_fu_108;
reg   [7:0] reuse_reg_fu_112;
reg   [7:0] win2_fu_116;
reg   [7:0] win1_fu_120;
reg   [7:0] win0_fu_124;
reg   [30:0] c_fu_128;
wire   [30:0] add_ln100_fu_454_p2;
reg   [30:0] r_fu_132;
wire   [30:0] select_ln98_1_fu_359_p3;
reg   [63:0] indvar_flatten_fu_136;
wire   [63:0] add_ln98_fu_324_p2;
reg   [7:0] win2_1_fu_140;
reg   [7:0] win1_1_fu_144;
reg   [7:0] win0_1_fu_148;
wire   [7:0] win0_5_fu_496_p3;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln100_1_fu_336_p1;
wire   [0:0] icmp_ln100_fu_340_p2;
wire   [30:0] add_ln98_1_fu_353_p2;
wire   [29:0] tmp_1_fu_367_p4;
wire   [30:0] select_ln98_fu_345_p3;
wire   [29:0] tmp_2_fu_432_p4;
wire   [0:0] icmp_fu_377_p2;
wire   [0:0] icmp_ln127_fu_442_p2;
wire   [8:0] zext_ln140_fu_564_p1;
wire   [8:0] zext_ln135_fu_540_p1;
wire   [8:0] sub_ln140_fu_568_p2;
wire   [8:0] shl_ln_fu_578_p3;
wire   [9:0] zext_ln140_1_fu_586_p1;
wire   [9:0] sub_ln140_1_fu_590_p2;
wire   [8:0] shl_ln140_1_fu_600_p3;
wire  signed [10:0] sext_ln140_1_fu_596_p1;
wire   [10:0] zext_ln135_5_fu_556_p1;
wire   [9:0] zext_ln140_2_fu_608_p1;
wire   [9:0] zext_ln135_2_fu_552_p1;
wire   [8:0] zext_ln135_4_fu_560_p1;
wire   [8:0] zext_ln135_1_fu_544_p1;
wire   [8:0] sub_ln141_fu_624_p2;
wire   [9:0] tmp_fu_630_p3;
wire  signed [10:0] sext_ln141_1_fu_638_p1;
wire   [10:0] add_ln141_fu_642_p2;
wire   [10:0] zext_ln135_3_fu_548_p1;
wire   [10:0] sub_ln141_1_fu_648_p2;
wire   [10:0] zext_ln140_3_fu_694_p1;
wire   [10:0] add_ln140_fu_690_p2;
wire  signed [10:0] gx_fu_697_p2;
wire   [10:0] sub_ln161_fu_710_p2;
wire  signed [31:0] sext_ln162_fu_716_p1;
wire   [0:0] tmp_4_fu_730_p3;
wire   [31:0] tmp_3_fu_720_p4;
wire  signed [31:0] sext_ln141_fu_703_p1;
wire   [10:0] sub_ln161_1_fu_746_p2;
wire  signed [31:0] sext_ln162_1_fu_751_p1;
wire  signed [31:0] sext_ln129_fu_707_p1;
wire   [0:0] tmp_6_fu_765_p3;
wire   [31:0] tmp_5_fu_755_p4;
wire   [31:0] select_ln163_1_fu_773_p3;
wire   [31:0] select_ln163_fu_738_p3;
wire   [31:0] mag_fu_781_p2;
wire   [0:0] xor_ln149_fu_797_p2;
wire   [0:0] and_ln147_fu_810_p2;
wire   [7:0] select_ln147_fu_802_p3;
wire   [7:0] select_ln147_1_fu_814_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 reuse_addr_reg27_fu_92 = 64'd0;
#0 reuse_reg26_fu_96 = 8'd0;
#0 reuse_addr_reg21_fu_100 = 64'd0;
#0 reuse_reg20_fu_104 = 8'd0;
#0 reuse_addr_reg_fu_108 = 64'd0;
#0 reuse_reg_fu_112 = 8'd0;
#0 win2_fu_116 = 8'd0;
#0 win1_fu_120 = 8'd0;
#0 win0_fu_124 = 8'd0;
#0 c_fu_128 = 31'd0;
#0 r_fu_132 = 31'd0;
#0 indvar_flatten_fu_136 = 64'd0;
#0 win2_1_fu_140 = 8'd0;
#0 win1_1_fu_144 = 8'd0;
#0 win0_1_fu_148 = 8'd0;
#0 ap_done_reg = 1'b0;
end

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959),
    .ce0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0),
    .we0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0),
    .d0(win1_5_fu_506_p3),
    .address1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1),
    .ce1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1),
    .q1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1)
);

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965),
    .ce0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0),
    .we0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0),
    .d0(win2_5_fu_517_p3),
    .address1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1),
    .ce1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1),
    .q1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1)
);

edge_detect_gauss_stage_Pipeline_Row_Loop_G_Col_Loop_G_gauss_stage_stream_ap_uint_8_0_strbkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971),
    .ce0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0),
    .we0(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0),
    .d0(gauss_stream_dout),
    .address1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1),
    .ce1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1),
    .q1(sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1)
);

edge_detect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_128 <= 31'd0;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_128 <= add_ln100_fu_454_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_136 <= 64'd0;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_136 <= add_ln98_fu_324_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_132 <= 31'd0;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            r_fu_132 <= select_ln98_1_fu_359_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg21_fu_100 <= 64'd18446744073709551615;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg21_fu_100 <= zext_ln100_fu_383_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg27_fu_92 <= 64'd18446744073709551615;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg27_fu_92 <= zext_ln100_fu_383_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_108 <= 64'd18446744073709551615;
        end else if (((icmp_ln98_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg_fu_108 <= zext_ln100_fu_383_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg20_fu_104 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_reg20_fu_104 <= win2_5_fu_517_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg26_fu_96 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_reg26_fu_96 <= win1_5_fu_506_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_112 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_reg_fu_112 <= gauss_stream_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win0_1_fu_148 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win0_1_fu_148 <= win0_5_fu_496_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win0_fu_124 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win0_fu_124 <= win0_1_fu_148;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win1_1_fu_144 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win1_1_fu_144 <= win1_5_fu_506_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win1_fu_120 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win1_fu_120 <= win1_1_fu_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win2_1_fu_140 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win2_1_fu_140 <= win2_5_fu_517_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win2_fu_116 <= 8'd0;
        end else if (((icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            win2_fu_116 <= win2_1_fu_140;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln140_1_reg_1008 <= add_ln140_1_fu_618_p2;
        and_ln127_reg_992_pp0_iter2_reg <= and_ln127_reg_992;
        and_ln127_reg_992_pp0_iter3_reg <= and_ln127_reg_992_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        gy_reg_1013 <= gy_fu_654_p2;
        icmp_ln147_reg_1019 <= icmp_ln147_fu_787_p2;
        icmp_ln149_reg_1024 <= icmp_ln149_fu_792_p2;
        sext_ln140_reg_998 <= sext_ln140_fu_574_p1;
        sub_ln140_2_reg_1003 <= sub_ln140_2_fu_612_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_cmp24_reg_982 <= addr_cmp24_fu_402_p2;
        addr_cmp30_reg_977 <= addr_cmp30_fu_393_p2;
        addr_cmp_reg_987 <= addr_cmp_fu_411_p2;
        and_ln127_reg_992 <= and_ln127_fu_448_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln98_reg_955 <= icmp_ln98_fu_319_p2;
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_addr_reg_965 <= zext_ln100_fu_383_p1;
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_addr_reg_959 <= zext_ln100_fu_383_p1;
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_addr_reg_971 <= zext_ln100_fu_383_p1;
    end
end

always @ (*) begin
    if (((icmp_ln98_fu_319_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln98_reg_955 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gauss_stream_blk_n = gauss_stream_empty_n;
    end else begin
        gauss_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gauss_stream_read = 1'b1;
    end else begin
        gauss_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln98_reg_955 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0 = 1'b1;
    end else begin
        sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_454_p2 = (select_ln98_fu_345_p3 + 31'd1);

assign add_ln140_1_fu_618_p2 = (zext_ln140_2_fu_608_p1 + zext_ln135_2_fu_552_p1);

assign add_ln140_fu_690_p2 = ($signed(sub_ln140_2_reg_1003) + $signed(sext_ln140_reg_998));

assign add_ln141_fu_642_p2 = ($signed(sext_ln141_1_fu_638_p1) + $signed(zext_ln135_5_fu_556_p1));

assign add_ln98_1_fu_353_p2 = (r_fu_132 + 31'd1);

assign add_ln98_fu_324_p2 = (indvar_flatten_fu_136 + 64'd1);

assign addr_cmp24_fu_402_p2 = ((reuse_addr_reg21_fu_100 == zext_ln100_fu_383_p1) ? 1'b1 : 1'b0);

assign addr_cmp30_fu_393_p2 = ((reuse_addr_reg27_fu_92 == zext_ln100_fu_383_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_411_p2 = ((reuse_addr_reg_fu_108 == zext_ln100_fu_383_p1) ? 1'b1 : 1'b0);

assign and_ln127_fu_448_p2 = (icmp_ln127_fu_442_p2 & icmp_fu_377_p2);

assign and_ln147_fu_810_p2 = (icmp_ln147_reg_1019 & and_ln127_reg_992_pp0_iter3_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln98_reg_955 == 1'd0) & (gauss_stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (out_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign gx_fu_697_p2 = (zext_ln140_3_fu_694_p1 + add_ln140_fu_690_p2);

assign gy_fu_654_p2 = ($signed(sub_ln141_1_fu_648_p2) + $signed(sext_ln140_fu_574_p1));

assign icmp_fu_377_p2 = ((tmp_1_fu_367_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln100_fu_340_p2 = (($signed(zext_ln100_1_fu_336_p1) < $signed(cols_load)) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_442_p2 = ((tmp_2_fu_432_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_787_p2 = (($signed(mag_fu_781_p2) < $signed(high_thresh_load)) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_792_p2 = (($signed(mag_fu_781_p2) < $signed(low_thresh_load)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_319_p2 = ((indvar_flatten_fu_136 == bound) ? 1'b1 : 1'b0);

assign mag_fu_781_p2 = (select_ln163_1_fu_773_p3 + select_ln163_fu_738_p3);

assign out_stream_TDATA = ((and_ln127_reg_992_pp0_iter3_reg[0:0] == 1'b1) ? select_ln147_1_fu_814_p3 : 8'd0);

assign select_ln147_1_fu_814_p3 = ((and_ln147_fu_810_p2[0:0] == 1'b1) ? select_ln147_fu_802_p3 : 8'd255);

assign select_ln147_fu_802_p3 = ((xor_ln149_fu_797_p2[0:0] == 1'b1) ? 8'd100 : 8'd0);

assign select_ln163_1_fu_773_p3 = ((tmp_6_fu_765_p3[0:0] == 1'b1) ? tmp_5_fu_755_p4 : sext_ln129_fu_707_p1);

assign select_ln163_fu_738_p3 = ((tmp_4_fu_730_p3[0:0] == 1'b1) ? tmp_3_fu_720_p4 : sext_ln141_fu_703_p1);

assign select_ln98_1_fu_359_p3 = ((icmp_ln100_fu_340_p2[0:0] == 1'b1) ? r_fu_132 : add_ln98_1_fu_353_p2);

assign select_ln98_fu_345_p3 = ((icmp_ln100_fu_340_p2[0:0] == 1'b1) ? c_fu_128 : 31'd0);

assign sext_ln129_fu_707_p1 = gy_reg_1013;

assign sext_ln140_1_fu_596_p1 = $signed(sub_ln140_1_fu_590_p2);

assign sext_ln140_fu_574_p1 = $signed(sub_ln140_fu_568_p2);

assign sext_ln141_1_fu_638_p1 = $signed(tmp_fu_630_p3);

assign sext_ln141_fu_703_p1 = gx_fu_697_p2;

assign sext_ln162_1_fu_751_p1 = $signed(sub_ln161_1_fu_746_p2);

assign sext_ln162_fu_716_p1 = $signed(sub_ln161_fu_710_p2);

assign shl_ln140_1_fu_600_p3 = {{win1_5_fu_506_p3}, {1'd0}};

assign shl_ln_fu_578_p3 = {{win1_fu_120}, {1'd0}};

assign sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_address1 = zext_ln100_fu_383_p1;

assign sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_address1 = zext_ln100_fu_383_p1;

assign sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_address1 = zext_ln100_fu_383_p1;

assign sub_ln140_1_fu_590_p2 = (10'd0 - zext_ln140_1_fu_586_p1);

assign sub_ln140_2_fu_612_p2 = ($signed(sext_ln140_1_fu_596_p1) - $signed(zext_ln135_5_fu_556_p1));

assign sub_ln140_fu_568_p2 = (zext_ln140_fu_564_p1 - zext_ln135_fu_540_p1);

assign sub_ln141_1_fu_648_p2 = (add_ln141_fu_642_p2 - zext_ln135_3_fu_548_p1);

assign sub_ln141_fu_624_p2 = (zext_ln135_4_fu_560_p1 - zext_ln135_1_fu_544_p1);

assign sub_ln161_1_fu_746_p2 = ($signed(11'd0) - $signed(gy_reg_1013));

assign sub_ln161_fu_710_p2 = ($signed(11'd0) - $signed(gx_fu_697_p2));

assign tmp_1_fu_367_p4 = {{select_ln98_1_fu_359_p3[30:1]}};

assign tmp_2_fu_432_p4 = {{select_ln98_fu_345_p3[30:1]}};

assign tmp_3_fu_720_p4 = {|(1'd0), sext_ln162_fu_716_p1[31 - 1:0]};

assign tmp_4_fu_730_p3 = gx_fu_697_p2[32'd10];

assign tmp_5_fu_755_p4 = {|(1'd0), sext_ln162_1_fu_751_p1[31 - 1:0]};

assign tmp_6_fu_765_p3 = sext_ln129_fu_707_p1[32'd31];

assign tmp_fu_630_p3 = {{sub_ln141_fu_624_p2}, {1'd0}};

assign win0_5_fu_496_p3 = ((addr_cmp30_reg_977[0:0] == 1'b1) ? reuse_reg26_fu_96 : sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_2_q1);

assign win1_5_fu_506_p3 = ((addr_cmp24_reg_982[0:0] == 1'b1) ? reuse_reg20_fu_104 : sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_1_q1);

assign win2_5_fu_517_p3 = ((addr_cmp_reg_987[0:0] == 1'b1) ? reuse_reg_fu_112 : sobel_stage_stream_stream_ap_uint_8_0_int_int_int_int_linebuf_q1);

assign xor_ln149_fu_797_p2 = (icmp_ln149_reg_1024 ^ 1'd1);

assign zext_ln100_1_fu_336_p1 = c_fu_128;

assign zext_ln100_fu_383_p1 = select_ln98_fu_345_p3;

assign zext_ln135_1_fu_544_p1 = win0_1_fu_148;

assign zext_ln135_2_fu_552_p1 = win0_5_fu_496_p3;

assign zext_ln135_3_fu_548_p1 = win0_5_fu_496_p3;

assign zext_ln135_4_fu_560_p1 = win2_1_fu_140;

assign zext_ln135_5_fu_556_p1 = win2_fu_116;

assign zext_ln135_fu_540_p1 = win0_fu_124;

assign zext_ln140_1_fu_586_p1 = shl_ln_fu_578_p3;

assign zext_ln140_2_fu_608_p1 = shl_ln140_1_fu_600_p3;

assign zext_ln140_3_fu_694_p1 = add_ln140_1_reg_1008;

assign zext_ln140_fu_564_p1 = win2_5_fu_517_p3;

endmodule //edge_detect_sobel_stage_Pipeline_Row_Loop_S_Col_Loop_S
