// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_edge_detect_Pipeline_gauss_loop_VITIS_LOOP_28_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        add_ln27,
        mul_ln27,
        blur_address0,
        blur_ce0,
        blur_we0,
        blur_d0,
        blur_1_address0,
        blur_1_ce0,
        blur_1_we0,
        blur_1_d0,
        blur_2_address0,
        blur_2_ce0,
        blur_2_we0,
        blur_2_d0,
        blur_3_address0,
        blur_3_ce0,
        blur_3_we0,
        blur_3_d0,
        blur_4_address0,
        blur_4_ce0,
        blur_4_we0,
        blur_4_d0,
        blur_5_address0,
        blur_5_ce0,
        blur_5_we0,
        blur_5_d0,
        blur_6_address0,
        blur_6_ce0,
        blur_6_we0,
        blur_6_d0,
        blur_7_address0,
        blur_7_ce0,
        blur_7_we0,
        blur_7_d0,
        blur_8_address0,
        blur_8_ce0,
        blur_8_we0,
        blur_8_d0,
        in_img
);

parameter    ap_ST_fsm_pp0_stage0 = 9'd1;
parameter    ap_ST_fsm_pp0_stage1 = 9'd2;
parameter    ap_ST_fsm_pp0_stage2 = 9'd4;
parameter    ap_ST_fsm_pp0_stage3 = 9'd8;
parameter    ap_ST_fsm_pp0_stage4 = 9'd16;
parameter    ap_ST_fsm_pp0_stage5 = 9'd32;
parameter    ap_ST_fsm_pp0_stage6 = 9'd64;
parameter    ap_ST_fsm_pp0_stage7 = 9'd128;
parameter    ap_ST_fsm_pp0_stage8 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] add_ln27;
input  [62:0] mul_ln27;
output  [15:0] blur_address0;
output   blur_ce0;
output   blur_we0;
output  [7:0] blur_d0;
output  [15:0] blur_1_address0;
output   blur_1_ce0;
output   blur_1_we0;
output  [7:0] blur_1_d0;
output  [15:0] blur_2_address0;
output   blur_2_ce0;
output   blur_2_we0;
output  [7:0] blur_2_d0;
output  [15:0] blur_3_address0;
output   blur_3_ce0;
output   blur_3_we0;
output  [7:0] blur_3_d0;
output  [15:0] blur_4_address0;
output   blur_4_ce0;
output   blur_4_we0;
output  [7:0] blur_4_d0;
output  [15:0] blur_5_address0;
output   blur_5_ce0;
output   blur_5_we0;
output  [7:0] blur_5_d0;
output  [15:0] blur_6_address0;
output   blur_6_ce0;
output   blur_6_we0;
output  [7:0] blur_6_d0;
output  [15:0] blur_7_address0;
output   blur_7_ce0;
output   blur_7_we0;
output  [7:0] blur_7_d0;
output  [15:0] blur_8_address0;
output   blur_8_ce0;
output   blur_8_we0;
output  [7:0] blur_8_d0;
input  [63:0] in_img;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg m_axi_gmem_RREADY;
reg blur_ce0;
reg blur_we0;
reg blur_1_ce0;
reg blur_1_we0;
reg blur_2_ce0;
reg blur_2_we0;
reg blur_3_ce0;
reg blur_3_we0;
reg blur_4_ce0;
reg blur_4_we0;
reg blur_5_ce0;
reg blur_5_we0;
reg blur_6_ce0;
reg blur_6_we0;
reg blur_7_ce0;
reg blur_7_we0;
reg blur_8_ce0;
reg blur_8_we0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage8;
reg   [0:0] icmp_ln27_reg_848;
reg    ap_block_state9_io;
reg    ap_block_state18_pp0_stage8_iter1;
reg    ap_block_pp0_stage8_subdone;
reg    ap_condition_exit_pp0_iter0_stage8;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage8;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
reg   [7:0] reg_322;
reg    ap_block_state14_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_state6_io;
reg    ap_block_state15_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
reg   [7:0] reg_326;
reg    ap_block_pp0_stage8_11001;
reg    ap_block_state19_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [30:0] c_2_reg_838;
reg    ap_block_state11_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln28_fu_365_p2;
reg   [0:0] icmp_ln28_reg_843;
wire   [0:0] icmp_ln27_fu_370_p2;
reg   [0:0] icmp_ln27_reg_848_pp0_iter1_reg;
reg   [0:0] icmp_ln27_reg_848_pp0_iter2_reg;
wire   [62:0] add_ln27_3_fu_375_p2;
reg   [62:0] add_ln27_3_reg_852;
wire   [30:0] select_ln27_fu_402_p3;
reg   [30:0] select_ln27_reg_857;
wire   [30:0] select_ln27_2_fu_410_p3;
reg   [30:0] select_ln27_2_reg_863;
wire   [30:0] select_ln27_3_fu_418_p3;
reg   [30:0] select_ln27_3_reg_868;
reg   [63:0] gmem_addr_reg_875;
wire   [63:0] tmp1_fu_487_p2;
reg   [63:0] tmp1_reg_881;
wire   [30:0] select_ln27_1_fu_492_p3;
reg   [30:0] select_ln27_1_reg_887;
reg    ap_block_state3_io;
reg    ap_block_state12_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
reg   [9:0] tmp_24_cast1_reg_894;
reg   [7:0] tmp_24_cast_reg_899;
reg   [63:0] gmem_addr_1_reg_904;
reg   [63:0] gmem_addr_2_reg_910;
reg   [15:0] udiv_ln_cast_reg_916;
reg    ap_block_state13_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
wire   [15:0] add_ln35_1_fu_607_p2;
reg   [15:0] add_ln35_1_reg_921;
reg   [15:0] add_ln35_1_reg_921_pp0_iter1_reg;
reg   [15:0] add_ln35_1_reg_921_pp0_iter2_reg;
reg   [15:0] add_ln35_1_reg_921_pp0_iter3_reg;
reg   [7:0] sum_reg_926;
reg   [7:0] gmem_addr_read_reg_931;
reg   [7:0] gmem_addr_read_1_reg_936;
wire   [8:0] tmp8_fu_651_p2;
reg   [8:0] tmp8_reg_941;
reg   [7:0] gmem_addr_1_read_2_reg_946;
reg    ap_block_state16_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg   [7:0] gmem_addr_2_read_reg_951;
reg    ap_block_state17_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_11001;
wire   [11:0] add_ln32_fu_698_p2;
reg   [11:0] add_ln32_reg_956;
reg   [7:0] trunc_ln2_reg_961;
reg   [7:0] trunc_ln2_reg_961_pp0_iter3_reg;
wire   [1:0] trunc_ln27_fu_767_p1;
reg   [1:0] trunc_ln27_reg_974;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln35_fu_771_p1;
wire   [63:0] empty_23_fu_475_p2;
wire   [63:0] empty_25_fu_541_p2;
wire   [63:0] empty_27_fu_562_p2;
reg   [30:0] c_fu_126;
wire   [30:0] add_ln28_fu_612_p2;
wire    ap_loop_init;
reg   [30:0] indvar1_fu_130;
wire   [30:0] add_ln28_1_fu_617_p2;
reg   [30:0] r_fu_134;
reg   [30:0] indvar_fu_138;
reg   [62:0] indvar_flatten_fu_142;
wire   [1:0] trunc_ln28_fu_783_p1;
reg   [30:0] grp_fu_317_p0;
wire   [62:0] zext_ln27_fu_498_p1;
wire   [62:0] zext_ln28_3_fu_573_p1;
wire   [32:0] grp_fu_317_p1;
wire   [31:0] zext_ln28_2_fu_361_p1;
wire   [30:0] add_ln27_2_fu_396_p2;
wire   [30:0] add_ln27_1_fu_390_p2;
wire   [30:0] grp_fu_426_p0;
wire   [2:0] grp_fu_426_p1;
wire   [40:0] p_shl_fu_436_p3;
wire   [36:0] p_shl3_fu_448_p3;
wire   [41:0] p_shl_cast_fu_444_p1;
wire   [41:0] p_shl3_cast_fu_456_p1;
wire   [41:0] empty_fu_460_p2;
wire   [63:0] zext_ln28_fu_432_p1;
wire   [63:0] tmp_fu_470_p2;
wire  signed [63:0] p_cast_fu_466_p1;
wire   [62:0] grp_fu_317_p2;
wire   [30:0] grp_fu_525_p0;
wire   [2:0] grp_fu_525_p1;
wire   [31:0] zext_ln28_1_fu_522_p1;
wire   [31:0] tmp2_fu_531_p2;
wire   [63:0] tmp2_cast_fu_537_p1;
wire   [31:0] tmp4_fu_552_p2;
wire   [63:0] tmp4_cast_fu_558_p1;
wire   [15:0] tmp_25_fu_587_p3;
wire   [15:0] tmp_27_fu_594_p3;
wire   [15:0] add_ln35_fu_601_p2;
wire   [8:0] gmem_addr_1_read_cast_fu_647_p1;
wire   [8:0] gmem_addr_read_1_cast_fu_644_p1;
wire   [8:0] gmem_addr_1_read_2_cast_fu_660_p1;
wire   [8:0] gmem_addr_2_read_1_cast_fu_663_p1;
wire   [8:0] tmp9_fu_670_p2;
wire   [9:0] tmp9_cast_fu_676_p1;
wire   [9:0] tmp8_cast_fu_667_p1;
wire   [9:0] tmp41_fu_680_p2;
wire   [10:0] tmp5_fu_686_p3;
wire   [11:0] zext_ln32_2_fu_694_p1;
wire   [11:0] gmem_addr_read_2_cast_fu_657_p1;
wire   [9:0] shl_ln_fu_707_p3;
wire   [11:0] zext_ln32_fu_715_p1;
wire   [8:0] zext_ln32_1_fu_719_p1;
wire   [8:0] gmem_addr_2_read_2_cast_fu_722_p1;
wire   [8:0] add_ln32_2_fu_731_p2;
wire   [9:0] zext_ln32_3_fu_737_p1;
wire   [9:0] zext_ln29_fu_704_p1;
wire   [9:0] add_ln32_3_fu_741_p2;
wire   [11:0] zext_ln32_4_fu_747_p1;
wire   [11:0] add_ln32_1_fu_726_p2;
wire   [11:0] sum_1_fu_751_p2;
wire   [1:0] grp_fu_426_p2;
wire   [1:0] grp_fu_525_p2;
reg    grp_fu_426_ce;
reg    grp_fu_525_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
reg    ap_done_pending_pp0;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 c_fu_126 = 31'd0;
#0 indvar1_fu_130 = 31'd0;
#0 r_fu_134 = 31'd0;
#0 indvar_fu_138 = 31'd0;
#0 indvar_flatten_fu_142 = 63'd0;
#0 ap_done_reg = 1'b0;
end

edge_detect_mul_31ns_33ns_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 63 ))
mul_31ns_33ns_63_1_1_U1(
    .din0(grp_fu_317_p0),
    .din1(grp_fu_317_p1),
    .dout(grp_fu_317_p2)
);

edge_detect_urem_31ns_3ns_2_35_1 #(
    .ID( 1 ),
    .NUM_STAGE( 35 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_31ns_3ns_2_35_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_426_p0),
    .din1(grp_fu_426_p1),
    .ce(grp_fu_426_ce),
    .dout(grp_fu_426_p2)
);

edge_detect_urem_31ns_3ns_2_35_1 #(
    .ID( 1 ),
    .NUM_STAGE( 35 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_31ns_3ns_2_35_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_525_p0),
    .din1(grp_fu_525_p1),
    .ce(grp_fu_525_ce),
    .dout(grp_fu_525_p2)
);

edge_detect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage8),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage8)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_126 <= 31'd1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
            c_fu_126 <= add_ln28_fu_612_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar1_fu_130 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
            indvar1_fu_130 <= add_ln28_1_fu_617_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_142 <= 63'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
            indvar_flatten_fu_142 <= add_ln27_3_reg_852;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_fu_138 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
            indvar_fu_138 <= select_ln27_2_reg_863;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_134 <= 31'd1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
            r_fu_134 <= select_ln27_3_reg_868;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln27_3_reg_852 <= add_ln27_3_fu_375_p2;
        c_2_reg_838 <= c_fu_126;
        gmem_addr_reg_875 <= empty_23_fu_475_p2;
        icmp_ln27_reg_848 <= icmp_ln27_fu_370_p2;
        icmp_ln27_reg_848_pp0_iter1_reg <= icmp_ln27_reg_848;
        icmp_ln27_reg_848_pp0_iter2_reg <= icmp_ln27_reg_848_pp0_iter1_reg;
        icmp_ln28_reg_843 <= icmp_ln28_fu_365_p2;
        select_ln27_2_reg_863 <= select_ln27_2_fu_410_p3;
        select_ln27_3_reg_868 <= select_ln27_3_fu_418_p3;
        select_ln27_reg_857 <= select_ln27_fu_402_p3;
        tmp1_reg_881 <= tmp1_fu_487_p2;
        trunc_ln2_reg_961 <= {{sum_1_fu_751_p2[11:4]}};
        trunc_ln2_reg_961_pp0_iter3_reg <= trunc_ln2_reg_961;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln32_reg_956 <= add_ln32_fu_698_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        add_ln35_1_reg_921 <= add_ln35_1_fu_607_p2;
        add_ln35_1_reg_921_pp0_iter1_reg <= add_ln35_1_reg_921;
        add_ln35_1_reg_921_pp0_iter2_reg <= add_ln35_1_reg_921_pp0_iter1_reg;
        add_ln35_1_reg_921_pp0_iter3_reg <= add_ln35_1_reg_921_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        gmem_addr_1_read_2_reg_946 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_addr_1_reg_904 <= empty_25_fu_541_p2;
        gmem_addr_2_reg_910 <= empty_27_fu_562_p2;
        select_ln27_1_reg_887 <= select_ln27_1_fu_492_p3;
        tmp_24_cast1_reg_894 <= {{grp_fu_317_p2[42:33]}};
        tmp_24_cast_reg_899 <= {{grp_fu_317_p2[40:33]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        gmem_addr_2_read_reg_951 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        gmem_addr_read_1_reg_936 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_addr_read_reg_931 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)))) begin
        reg_322 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)))) begin
        reg_326 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sum_reg_926 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        tmp8_reg_941 <= tmp8_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        trunc_ln27_reg_974 <= trunc_ln27_fu_767_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        udiv_ln_cast_reg_916 <= {{grp_fu_317_p2[48:33]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone) & (icmp_ln27_reg_848 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln27_reg_848_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_1_ce0 = 1'b1;
    end else begin
        blur_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln28_fu_783_p1 == 2'd1) & (trunc_ln27_reg_974 == 2'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_1_we0 = 1'b1;
    end else begin
        blur_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_2_ce0 = 1'b1;
    end else begin
        blur_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln28_fu_783_p1 == 2'd0) & ~(trunc_ln28_fu_783_p1 == 2'd1) & (trunc_ln27_reg_974 == 2'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_2_we0 = 1'b1;
    end else begin
        blur_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_3_ce0 = 1'b1;
    end else begin
        blur_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln28_fu_783_p1 == 2'd0) & (trunc_ln27_reg_974 == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_3_we0 = 1'b1;
    end else begin
        blur_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_4_ce0 = 1'b1;
    end else begin
        blur_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln28_fu_783_p1 == 2'd1) & (trunc_ln27_reg_974 == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_4_we0 = 1'b1;
    end else begin
        blur_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_5_ce0 = 1'b1;
    end else begin
        blur_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln28_fu_783_p1 == 2'd0) & ~(trunc_ln28_fu_783_p1 == 2'd1) & (trunc_ln27_reg_974 == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_5_we0 = 1'b1;
    end else begin
        blur_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_6_ce0 = 1'b1;
    end else begin
        blur_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln27_reg_974 == 2'd0) & ~(trunc_ln27_reg_974 == 2'd1) & (trunc_ln28_fu_783_p1 == 2'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_6_we0 = 1'b1;
    end else begin
        blur_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_7_ce0 = 1'b1;
    end else begin
        blur_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln27_reg_974 == 2'd0) & ~(trunc_ln27_reg_974 == 2'd1) & (trunc_ln28_fu_783_p1 == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_7_we0 = 1'b1;
    end else begin
        blur_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_8_ce0 = 1'b1;
    end else begin
        blur_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln27_reg_974 == 2'd0) & ~(trunc_ln28_fu_783_p1 == 2'd0) & ~(trunc_ln28_fu_783_p1 == 2'd1) & ~(trunc_ln27_reg_974 == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_8_we0 = 1'b1;
    end else begin
        blur_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_ce0 = 1'b1;
    end else begin
        blur_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln28_fu_783_p1 == 2'd0) & (trunc_ln27_reg_974 == 2'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        blur_we0 = 1'b1;
    end else begin
        blur_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8) & (icmp_ln27_reg_848 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5) & (icmp_ln27_reg_848 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln27_reg_848 == 1'd0)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
            grp_fu_317_p0 = zext_ln28_3_fu_573_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
            grp_fu_317_p0 = zext_ln27_fu_498_p1;
        end else begin
            grp_fu_317_p0 = 'bx;
        end
    end else begin
        grp_fu_317_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        grp_fu_426_ce = 1'b1;
    end else begin
        grp_fu_426_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        grp_fu_525_ce = 1'b1;
    end else begin
        grp_fu_525_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln27_reg_848 == 1'd0))) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
            m_axi_gmem_ARADDR = gmem_addr_2_reg_910;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
            m_axi_gmem_ARADDR = gmem_addr_1_reg_904;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
            m_axi_gmem_ARADDR = gmem_addr_reg_875;
        end else begin
            m_axi_gmem_ARADDR = 'bx;
        end
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001) & (icmp_ln27_reg_848 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln27_reg_848 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln27_reg_848 == 1'd0)))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_1_fu_390_p2 = (r_fu_134 + 31'd1);

assign add_ln27_2_fu_396_p2 = (indvar_fu_138 + 31'd1);

assign add_ln27_3_fu_375_p2 = (indvar_flatten_fu_142 + 63'd1);

assign add_ln28_1_fu_617_p2 = (select_ln27_reg_857 + 31'd1);

assign add_ln28_fu_612_p2 = (select_ln27_1_reg_887 + 31'd1);

assign add_ln32_1_fu_726_p2 = (add_ln32_reg_956 + zext_ln32_fu_715_p1);

assign add_ln32_2_fu_731_p2 = (zext_ln32_1_fu_719_p1 + gmem_addr_2_read_2_cast_fu_722_p1);

assign add_ln32_3_fu_741_p2 = (zext_ln32_3_fu_737_p1 + zext_ln29_fu_704_p1);

assign add_ln32_fu_698_p2 = (zext_ln32_2_fu_694_p1 + gmem_addr_read_2_cast_fu_657_p1);

assign add_ln35_1_fu_607_p2 = (add_ln35_fu_601_p2 + udiv_ln_cast_reg_916);

assign add_ln35_fu_601_p2 = (tmp_25_fu_587_p3 + tmp_27_fu_594_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter2));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage3_iter1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage3_iter1));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage4_iter1));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage4_iter1));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage5_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage5_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage6_iter1));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage6_iter1));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage7_iter1));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage7_iter1));
end

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage8_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage8_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage8_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_state11_pp0_stage1_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage2_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state13_pp0_stage3_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state14_pp0_stage4_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state15_pp0_stage5_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state16_pp0_stage6_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage7_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_pp0_stage8_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp0_stage0_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln27_reg_848 == 1'd0));
end

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln27_reg_848 == 1'd0));
end

always @ (*) begin
    ap_block_state9_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln27_reg_848 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage8;

assign blur_1_address0 = zext_ln35_fu_771_p1;

assign blur_1_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_2_address0 = zext_ln35_fu_771_p1;

assign blur_2_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_3_address0 = zext_ln35_fu_771_p1;

assign blur_3_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_4_address0 = zext_ln35_fu_771_p1;

assign blur_4_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_5_address0 = zext_ln35_fu_771_p1;

assign blur_5_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_6_address0 = zext_ln35_fu_771_p1;

assign blur_6_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_7_address0 = zext_ln35_fu_771_p1;

assign blur_7_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_8_address0 = zext_ln35_fu_771_p1;

assign blur_8_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign blur_address0 = zext_ln35_fu_771_p1;

assign blur_d0 = trunc_ln2_reg_961_pp0_iter3_reg;

assign empty_23_fu_475_p2 = ($signed(tmp_fu_470_p2) + $signed(p_cast_fu_466_p1));

assign empty_25_fu_541_p2 = (tmp2_cast_fu_537_p1 + tmp1_reg_881);

assign empty_27_fu_562_p2 = (tmp4_cast_fu_558_p1 + tmp1_reg_881);

assign empty_fu_460_p2 = (p_shl_cast_fu_444_p1 - p_shl3_cast_fu_456_p1);

assign gmem_addr_1_read_2_cast_fu_660_p1 = gmem_addr_1_read_2_reg_946;

assign gmem_addr_1_read_cast_fu_647_p1 = reg_322;

assign gmem_addr_2_read_1_cast_fu_663_p1 = reg_326;

assign gmem_addr_2_read_2_cast_fu_722_p1 = reg_326;

assign gmem_addr_read_1_cast_fu_644_p1 = gmem_addr_read_reg_931;

assign gmem_addr_read_2_cast_fu_657_p1 = gmem_addr_read_1_reg_936;

assign grp_fu_317_p1 = 63'd2863311531;

assign grp_fu_426_p0 = ((icmp_ln28_fu_365_p2[0:0] == 1'b1) ? r_fu_134 : add_ln27_1_fu_390_p2);

assign grp_fu_426_p1 = 31'd3;

assign grp_fu_525_p0 = ((icmp_ln28_reg_843[0:0] == 1'b1) ? c_2_reg_838 : 31'd1);

assign grp_fu_525_p1 = 31'd3;

assign icmp_ln27_fu_370_p2 = ((indvar_flatten_fu_142 == mul_ln27) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_365_p2 = (($signed(zext_ln28_2_fu_361_p1) < $signed(add_ln27)) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd3;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 8'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign p_cast_fu_466_p1 = $signed(empty_fu_460_p2);

assign p_shl3_cast_fu_456_p1 = p_shl3_fu_448_p3;

assign p_shl3_fu_448_p3 = {{select_ln27_2_fu_410_p3}, {6'd0}};

assign p_shl_cast_fu_444_p1 = p_shl_fu_436_p3;

assign p_shl_fu_436_p3 = {{select_ln27_2_fu_410_p3}, {10'd0}};

assign select_ln27_1_fu_492_p3 = ((icmp_ln28_reg_843[0:0] == 1'b1) ? c_2_reg_838 : 31'd1);

assign select_ln27_2_fu_410_p3 = ((icmp_ln28_fu_365_p2[0:0] == 1'b1) ? indvar_fu_138 : add_ln27_2_fu_396_p2);

assign select_ln27_3_fu_418_p3 = ((icmp_ln28_fu_365_p2[0:0] == 1'b1) ? r_fu_134 : add_ln27_1_fu_390_p2);

assign select_ln27_fu_402_p3 = ((icmp_ln28_fu_365_p2[0:0] == 1'b1) ? indvar1_fu_130 : 31'd0);

assign shl_ln_fu_707_p3 = {{reg_322}, {2'd0}};

assign sum_1_fu_751_p2 = (zext_ln32_4_fu_747_p1 + add_ln32_1_fu_726_p2);

assign tmp1_fu_487_p2 = ($signed(p_cast_fu_466_p1) + $signed(in_img));

assign tmp2_cast_fu_537_p1 = tmp2_fu_531_p2;

assign tmp2_fu_531_p2 = (zext_ln28_1_fu_522_p1 + 32'd960);

assign tmp41_fu_680_p2 = (tmp9_cast_fu_676_p1 + tmp8_cast_fu_667_p1);

assign tmp4_cast_fu_558_p1 = tmp4_fu_552_p2;

assign tmp4_fu_552_p2 = (zext_ln28_1_fu_522_p1 + 32'd1920);

assign tmp5_fu_686_p3 = {{tmp41_fu_680_p2}, {1'd0}};

assign tmp8_cast_fu_667_p1 = tmp8_reg_941;

assign tmp8_fu_651_p2 = (gmem_addr_1_read_cast_fu_647_p1 + gmem_addr_read_1_cast_fu_644_p1);

assign tmp9_cast_fu_676_p1 = tmp9_fu_670_p2;

assign tmp9_fu_670_p2 = (gmem_addr_1_read_2_cast_fu_660_p1 + gmem_addr_2_read_1_cast_fu_663_p1);

assign tmp_25_fu_587_p3 = {{tmp_24_cast_reg_899}, {8'd0}};

assign tmp_27_fu_594_p3 = {{tmp_24_cast1_reg_894}, {6'd0}};

assign tmp_fu_470_p2 = (zext_ln28_fu_432_p1 + in_img);

assign trunc_ln27_fu_767_p1 = grp_fu_426_p2[1:0];

assign trunc_ln28_fu_783_p1 = grp_fu_525_p2[1:0];

assign zext_ln27_fu_498_p1 = select_ln27_3_reg_868;

assign zext_ln28_1_fu_522_p1 = select_ln27_reg_857;

assign zext_ln28_2_fu_361_p1 = c_fu_126;

assign zext_ln28_3_fu_573_p1 = select_ln27_1_reg_887;

assign zext_ln28_fu_432_p1 = select_ln27_fu_402_p3;

assign zext_ln29_fu_704_p1 = sum_reg_926;

assign zext_ln32_1_fu_719_p1 = gmem_addr_2_read_reg_951;

assign zext_ln32_2_fu_694_p1 = tmp5_fu_686_p3;

assign zext_ln32_3_fu_737_p1 = add_ln32_2_fu_731_p2;

assign zext_ln32_4_fu_747_p1 = add_ln32_3_fu_741_p2;

assign zext_ln32_fu_715_p1 = shl_ln_fu_707_p3;

assign zext_ln35_fu_771_p1 = add_ln35_1_reg_921_pp0_iter3_reg;

endmodule //edge_detect_edge_detect_Pipeline_gauss_loop_VITIS_LOOP_28_1
