// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_edge_detect_Pipeline_thresh_loop_VITIS_LOOP_58_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        add_ln27,
        mul_ln27,
        grad_mag_address0,
        grad_mag_ce0,
        grad_mag_q0,
        out_img,
        high_thresh,
        low_thresh
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] add_ln27;
input  [62:0] mul_ln27;
output  [18:0] grad_mag_address0;
output   grad_mag_ce0;
input  [31:0] grad_mag_q0;
input  [63:0] out_img;
input  [31:0] high_thresh;
input  [31:0] low_thresh;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg[7:0] m_axi_gmem_WDATA;
reg m_axi_gmem_BREADY;
reg grad_mag_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln60_reg_445;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln60_reg_445_pp0_iter3_reg;
reg    ap_block_state5_io;
reg   [0:0] icmp_ln60_reg_445_pp0_iter8_reg;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_211_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg   [63:0] reg_173;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln60_fu_362_p2;
wire   [63:0] add_ln59_1_fu_335_p2;
reg   [63:0] add_ln59_1_reg_440;
reg   [0:0] icmp_ln60_reg_445_pp0_iter4_reg;
reg   [0:0] icmp_ln60_reg_445_pp0_iter5_reg;
reg   [0:0] icmp_ln60_reg_445_pp0_iter6_reg;
reg   [0:0] icmp_ln60_reg_445_pp0_iter7_reg;
wire   [0:0] icmp_ln62_fu_367_p2;
reg   [0:0] icmp_ln62_reg_449;
wire   [7:0] select_ln62_cast_cast_cast_cast_fu_377_p3;
reg   [7:0] select_ln62_cast_cast_cast_cast_reg_454;
wire   [63:0] zext_ln59_2_fu_307_p1;
reg    ap_block_pp0_stage0_01001;
reg   [30:0] c_fu_80;
wire   [30:0] add_ln58_fu_341_p2;
wire    ap_loop_init;
reg   [30:0] r_fu_84;
wire   [30:0] select_ln57_1_fu_239_p3;
reg   [62:0] indvar_flatten19_fu_88;
wire   [62:0] add_ln57_1_fu_216_p2;
wire   [31:0] zext_ln58_1_fu_202_p1;
wire   [0:0] icmp_ln58_fu_206_p2;
wire   [30:0] add_ln57_fu_225_p2;
wire   [8:0] trunc_ln59_fu_247_p1;
wire   [12:0] trunc_ln59_1_fu_267_p1;
wire   [18:0] tmp_43_cast_fu_259_p3;
wire   [18:0] tmp_44_cast_fu_279_p3;
wire   [30:0] select_ln57_fu_231_p3;
wire   [18:0] sub_ln59_1_fu_287_p2;
wire   [18:0] trunc_ln59_2_fu_297_p1;
wire   [18:0] add_ln59_2_fu_301_p2;
wire   [40:0] tmp_s_fu_251_p3;
wire   [36:0] tmp_1_fu_271_p3;
wire   [41:0] zext_ln59_fu_312_p1;
wire   [41:0] zext_ln59_1_fu_316_p1;
wire   [41:0] sub_ln59_fu_320_p2;
wire   [63:0] zext_ln58_fu_293_p1;
wire   [63:0] add_ln59_fu_330_p2;
wire  signed [63:0] sext_ln59_fu_326_p1;
wire   [0:0] xor_ln62_fu_372_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 c_fu_80 = 31'd0;
#0 r_fu_84 = 31'd0;
#0 indvar_flatten19_fu_88 = 63'd0;
#0 ap_done_reg = 1'b0;
end

edge_detect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_80 <= 31'd1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln57_fu_211_p2 == 1'd0))) begin
            c_fu_80 <= add_ln58_fu_341_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_88 <= 63'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln57_fu_211_p2 == 1'd0))) begin
            indvar_flatten19_fu_88 <= add_ln57_1_fu_216_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_84 <= 31'd1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln57_fu_211_p2 == 1'd0))) begin
            r_fu_84 <= select_ln57_1_fu_239_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln59_1_reg_440 <= add_ln59_1_fu_335_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln60_reg_445 <= icmp_ln60_fu_362_p2;
        icmp_ln60_reg_445_pp0_iter3_reg <= icmp_ln60_reg_445;
        icmp_ln60_reg_445_pp0_iter4_reg <= icmp_ln60_reg_445_pp0_iter3_reg;
        icmp_ln60_reg_445_pp0_iter5_reg <= icmp_ln60_reg_445_pp0_iter4_reg;
        icmp_ln60_reg_445_pp0_iter6_reg <= icmp_ln60_reg_445_pp0_iter5_reg;
        icmp_ln60_reg_445_pp0_iter7_reg <= icmp_ln60_reg_445_pp0_iter6_reg;
        icmp_ln60_reg_445_pp0_iter8_reg <= icmp_ln60_reg_445_pp0_iter7_reg;
        icmp_ln62_reg_449 <= icmp_ln62_fu_367_p2;
        select_ln62_cast_cast_cast_cast_reg_454[2] <= select_ln62_cast_cast_cast_cast_fu_377_p3[2];
select_ln62_cast_cast_cast_cast_reg_454[6 : 5] <= select_ln62_cast_cast_cast_cast_fu_377_p3[6 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_fu_362_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_fu_362_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_173 <= add_ln59_1_reg_440;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln57_fu_211_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445 == 1'd1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445 == 1'd0)))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445_pp0_iter8_reg == 1'd1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445_pp0_iter8_reg == 1'd0)))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd0)))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grad_mag_ce0 = 1'b1;
    end else begin
        grad_mag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445 == 1'd1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445 == 1'd0)))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445_pp0_iter8_reg == 1'd1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445_pp0_iter8_reg == 1'd0)))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        if ((icmp_ln60_reg_445_pp0_iter3_reg == 1'd1)) begin
            m_axi_gmem_WDATA = select_ln62_cast_cast_cast_cast_reg_454;
        end else if ((icmp_ln60_reg_445_pp0_iter3_reg == 1'd0)) begin
            m_axi_gmem_WDATA = 8'd255;
        end else begin
            m_axi_gmem_WDATA = 'bx;
        end
    end else begin
        m_axi_gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd0)))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_1_fu_216_p2 = (indvar_flatten19_fu_88 + 63'd1);

assign add_ln57_fu_225_p2 = (r_fu_84 + 31'd1);

assign add_ln58_fu_341_p2 = (select_ln57_fu_231_p3 + 31'd1);

assign add_ln59_1_fu_335_p2 = ($signed(add_ln59_fu_330_p2) + $signed(sext_ln59_fu_326_p1));

assign add_ln59_2_fu_301_p2 = (sub_ln59_1_fu_287_p2 + trunc_ln59_2_fu_297_p1);

assign add_ln59_fu_330_p2 = (zext_ln58_fu_293_p1 + out_img);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (((icmp_ln60_reg_445_pp0_iter8_reg == 1'd1) & (m_axi_gmem_BVALID == 1'b0)) | ((icmp_ln60_reg_445_pp0_iter8_reg == 1'd0) & (m_axi_gmem_BVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = (((m_axi_gmem_AWREADY == 1'b0) & (icmp_ln60_reg_445 == 1'd1)) | ((m_axi_gmem_AWREADY == 1'b0) & (icmp_ln60_reg_445 == 1'd0)));
end

always @ (*) begin
    ap_block_state5_io = (((m_axi_gmem_WREADY == 1'b0) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd1)) | ((m_axi_gmem_WREADY == 1'b0) & (icmp_ln60_reg_445_pp0_iter3_reg == 1'd0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign grad_mag_address0 = zext_ln59_2_fu_307_p1;

assign icmp_ln57_fu_211_p2 = ((indvar_flatten19_fu_88 == mul_ln27) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_206_p2 = (($signed(zext_ln58_1_fu_202_p1) < $signed(add_ln27)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_362_p2 = (($signed(grad_mag_q0) < $signed(high_thresh)) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_367_p2 = (($signed(grad_mag_q0) < $signed(low_thresh)) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = reg_173;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd1;

assign m_axi_gmem_WUSER = 1'd0;

assign select_ln57_1_fu_239_p3 = ((icmp_ln58_fu_206_p2[0:0] == 1'b1) ? r_fu_84 : add_ln57_fu_225_p2);

assign select_ln57_fu_231_p3 = ((icmp_ln58_fu_206_p2[0:0] == 1'b1) ? c_fu_80 : 31'd1);

assign select_ln62_cast_cast_cast_cast_fu_377_p3 = ((xor_ln62_fu_372_p2[0:0] == 1'b1) ? 8'd100 : 8'd0);

assign sext_ln59_fu_326_p1 = $signed(sub_ln59_fu_320_p2);

assign sub_ln59_1_fu_287_p2 = (tmp_43_cast_fu_259_p3 - tmp_44_cast_fu_279_p3);

assign sub_ln59_fu_320_p2 = (zext_ln59_fu_312_p1 - zext_ln59_1_fu_316_p1);

assign tmp_1_fu_271_p3 = {{select_ln57_1_fu_239_p3}, {6'd0}};

assign tmp_43_cast_fu_259_p3 = {{trunc_ln59_fu_247_p1}, {10'd0}};

assign tmp_44_cast_fu_279_p3 = {{trunc_ln59_1_fu_267_p1}, {6'd0}};

assign tmp_s_fu_251_p3 = {{select_ln57_1_fu_239_p3}, {10'd0}};

assign trunc_ln59_1_fu_267_p1 = select_ln57_1_fu_239_p3[12:0];

assign trunc_ln59_2_fu_297_p1 = select_ln57_fu_231_p3[18:0];

assign trunc_ln59_fu_247_p1 = select_ln57_1_fu_239_p3[8:0];

assign xor_ln62_fu_372_p2 = (icmp_ln62_reg_449 ^ 1'd1);

assign zext_ln58_1_fu_202_p1 = c_fu_80;

assign zext_ln58_fu_293_p1 = select_ln57_fu_231_p3;

assign zext_ln59_1_fu_316_p1 = tmp_1_fu_271_p3;

assign zext_ln59_2_fu_307_p1 = add_ln59_2_fu_301_p2;

assign zext_ln59_fu_312_p1 = tmp_s_fu_251_p3;

always @ (posedge ap_clk) begin
    select_ln62_cast_cast_cast_cast_reg_454[1:0] <= 2'b00;
    select_ln62_cast_cast_cast_cast_reg_454[4:3] <= 2'b00;
    select_ln62_cast_cast_cast_cast_reg_454[7] <= 1'b0;
end

endmodule //edge_detect_edge_detect_Pipeline_thresh_loop_VITIS_LOOP_58_7
